import 'dart:io';

import 'package:flutter/services.dart' show rootBundle;
import 'package:vdodtor_engine/vdodtor_engine.dart';

/// One bundled look: the name a clip stores, and the file it lives in.
typedef BundledLook = ({String name, String asset});

/// The colour looks the app ships, and the ones the user has added.
///
/// A look is the half of a grade that cannot be a matrix — see
/// `engine/include/vdodtor/vd_lut.h`. The five sliders in the inspector are
/// all affine on RGB and fold into one 3x3; a split-tone, a film curve or a
/// bleach bypass do not, so they arrive as a lookup table instead.
///
/// **A look is a name, and the name is what the project file records.** That
/// is what makes a graded project portable between machines: the file says
/// "Warm Film", not where this computer keeps its cubes. It is the same
/// bargain [BundledFonts] makes, and it has the same failure mode — a project
/// naming a look this installation does not have draws ungraded, exactly as a
/// caption in a missing face falls back to the system's.
///
/// **A `.cube` the user loads is copied into their library rather than linked
/// to.** Three reasons, and any one of them would do. A path into
/// `~/Downloads` is a path that breaks the first time somebody tidies up. Under
/// the sandbox, reaching outside the container needs a security-scoped bookmark
/// that has to be minted, stored and resolved — for a file that is a hundred
/// kilobytes and never changes. And a look is not project material the way a
/// video clip is: it is a tool, and somebody who loads one wants it on the next
/// project too.
abstract final class BundledLooks {
  /// Every look the app ships, in the order the picker should offer them.
  ///
  /// Generated by `tools/make_luts.dart` rather than vendored, because a look
  /// that ships in a product sold without an account has to be one we are
  /// allowed to sell — and the `.cube` files people share almost never are.
  /// Each is a formula in that file; the `.cube` is what the formula evaluates
  /// to.
  ///
  /// The names are written here as well as being the keys the engine
  /// registers, the same duplication [BundledFonts.faces] has and for the same
  /// reason: the picker lists looks before an engine exists — a widget test has
  /// none — so asking the engine at build time would make the inspector
  /// unbuildable without one.
  static const looks = <BundledLook>[
    (name: 'Warm Film', asset: 'assets/luts/warm_film.cube'),
    (name: 'Teal & Orange', asset: 'assets/luts/teal_orange.cube'),
    (name: 'Bleach Bypass', asset: 'assets/luts/bleach_bypass.cube'),
    (name: 'Faded', asset: 'assets/luts/faded.cube'),
    (name: 'Noir', asset: 'assets/luts/noir.cube'),
  ];

  /// What a clip with no look on it stores. The empty string all the way down
  /// to `VdTimelineClip::look`, which takes NULL for the same thing.
  static const none = '';

  static List<String> get names => [for (final l in looks) l.name];

  /// Every look that can be picked right now: the bundled ones, and whatever
  /// the user has added to their library.
  ///
  /// Kept on this side rather than read back from `Looks.names`, for the
  /// reason [looks] is written down here at all: the inspector lists looks
  /// with no engine alive — a widget test has none — and a picker that had to
  /// ask the engine would be a picker nothing could test. The two are the same
  /// list because this is the only thing that registers one.
  static List<String> get available => List.unmodifiable(_available);
  static final List<String> _available = [for (final l in looks) l.name];

  /// The extension an open panel should filter on, and the only one a `.cube`
  /// has.
  static const extension = 'cube';

  static bool _loaded = false;

  /// Registers every bundled look with the engine, and every look in
  /// [libraryOf] beside them.
  ///
  /// Idempotent, because a hot restart runs it again and the engine's own
  /// catalogue drops the repeats. Awaited before the first project opens: a
  /// clip naming a look that has not been registered yet renders ungraded, and
  /// registering afterwards would not redraw it.
  ///
  /// A look that will not parse is skipped rather than thrown, because the
  /// user's own library is in it: one bad file somebody dropped in a folder
  /// must not stop the app launching.
  static Future<void> load({Directory? library}) async {
    if (_loaded && library == null) return;
    for (final look in looks) {
      final data = await rootBundle.load(look.asset);
      Looks.register(look.name, data.buffer.asUint8List());
    }
    // Registration is idempotent and so is this: a hot restart runs the whole
    // of load() again, and the picker must not end up offering everything
    // twice.
    _available
      ..clear()
      ..addAll(names);
    if (library != null) await _loadLibrary(library);
    _loaded = true;
  }

  static Future<void> _loadLibrary(Directory library) async {
    if (!library.existsSync()) return;
    // Sorted, so the picker lists them the same way twice running: the
    // filesystem's own order is not an order anybody chose.
    final files = library
        .listSync()
        .whereType<File>()
        .where((f) => f.path.toLowerCase().endsWith('.$extension'))
        .toList()
      ..sort((a, b) => a.path.compareTo(b.path));
    for (final file in files) {
      try {
        final name = nameOf(file.path);
        Looks.register(name, await file.readAsBytes());
        if (!_available.contains(name)) _available.add(name);
      } on Exception {
        // A file that is not a look is one the user can delete. Refusing to
        // launch over it would be a worse answer than leaving it out.
        continue;
      }
    }
  }

  /// Where the user's own looks are kept: beside the app's other private
  /// state, and *not* in the project folder.
  ///
  /// A look is a tool rather than project material — two projects using one
  /// look should share it, and a project copied to another machine should not
  /// carry a copy of every filter it happens to use. That is the same
  /// reasoning `AppPaths.peaks` is built on.
  static Directory libraryOf(Directory support) =>
      Directory('${support.path}/Looks');

  /// Copies [path] into [library] and registers it, and hands back the name a
  /// clip should store.
  ///
  /// The name is the file's own, so a look called `Kodak 2383.cube` is offered
  /// as "Kodak 2383" — what the user called it is what they will look for. A
  /// second file with a name already taken is stored under `name 2`, because
  /// silently replacing the first would change every clip already wearing it.
  static Future<String> import(String path, {required Directory library}) async {
    final source = File(path);
    final bytes = await source.readAsBytes();
    // Parsed *before* anything is copied: a file that is not a look should
    // leave no trace and say so, rather than landing in the library to fail
    // again at every launch.
    final taken = _available.toSet();
    var name = nameOf(path);
    for (var n = 2; taken.contains(name); n++) {
      name = '${nameOf(path)} $n';
    }
    Looks.register(name, bytes);

    await library.create(recursive: true);
    await File('${library.path}/$name.$extension').writeAsBytes(bytes);
    _available.add(name);
    return name;
  }

  /// The look name a `.cube` at [path] is offered under: its file name without
  /// the extension.
  static String nameOf(String path) {
    final base = path.split(Platform.pathSeparator).last;
    final dot = base.lastIndexOf('.');
    return dot > 0 ? base.substring(0, dot) : base;
  }
}
