/// The About sheet: which build this is, and what is in it that we did not
/// write.
///
/// It exists because of the second half. FFmpeg is LGPL 2.1, and §6 asks for
/// prominent notice, a copy of the licence, and enough information to build a
/// replacement library and drop it in — obligations that are only discharged
/// if somebody running the app can actually reach them. A NOTICES file in a
/// repository is not that; neither is one in a disk image, which is a thing
/// people throw away the day they mount it. So the notice and the licence ship
/// as assets and this sheet shows both, verbatim.
///
/// Verbatim is the point. The notice is generated by `tools/make_notices.dart`
/// from the files actually vendored, and rendering it into prettier widgets
/// would make a second document that could disagree with the first about a
/// version number — which for a licence obligation is the one kind of drift
/// worse than a crash.
library;

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:vdodtor_engine/vdodtor_engine.dart';

import '../app/about.dart';
import 'theme.dart';

/// Shows the sheet. Resolves when it is closed.
Future<void> showAboutSheet(BuildContext context) => showDialog<void>(
      context: context,
      builder: (_) => const _AboutSheet(),
    );

/// Which of the two documents the box is showing.
enum _Document {
  notices('Third-party notices', About.noticesAsset),
  licence('LGPL 2.1', About.licenceAsset);

  const _Document(this.label, this.asset);

  final String label;
  final String asset;
}

class _AboutSheet extends StatefulWidget {
  const _AboutSheet();

  @override
  State<_AboutSheet> createState() => _AboutSheetState();
}

class _AboutSheetState extends State<_AboutSheet> {
  _Document _showing = _Document.notices;

  /// What each document says, once it has been read. Kept for the life of the
  /// sheet rather than re-read on every tap of the selector, and dropped with
  /// it: see [About.read].
  final Map<_Document, String> _text = {};

  /// Set when a link could not be opened, on the licence sheet's terms: a
  /// button that silently does nothing is the one failure a user cannot
  /// report.
  String? _linkFailure;

  @override
  void initState() {
    super.initState();
    unawaited(_load(_showing));
  }

  Future<void> _load(_Document document) async {
    if (_text.containsKey(document)) return;
    final text = await About.read(document.asset);
    if (!mounted) return;
    setState(() => _text[document] = text);
  }

  void _show(_Document document) {
    setState(() => _showing = document);
    unawaited(_load(document));
  }

  Future<void> _openSource() async {
    final opened = await SystemLinks.open(About.source);
    if (!mounted || opened) return;
    setState(() => _linkFailure = About.source.toString());
  }

  @override
  Widget build(BuildContext context) => AlertDialog(
        backgroundColor: VdColors.panel,
        contentPadding: const EdgeInsets.fromLTRB(24, 20, 24, 8),
        content: SizedBox(
          width: 560,
          height: 420,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text('vdodtor',
                  style: TextStyle(
                    fontSize: 26,
                    fontWeight: FontWeight.w700,
                    letterSpacing: -0.8,
                  )),
              const SizedBox(height: 2),
              const Text(
                'Version ${About.version} · ${About.copyright}',
                style: TextStyle(fontSize: 11, color: VdColors.dim),
              ),
              const SizedBox(height: 14),
              const Text(
                'A video editor with no watermark, no account and no ads. It '
                'has no network access at all: your footage never leaves this '
                'machine, because there is nowhere for it to go.',
                style: TextStyle(fontSize: 12, color: VdColors.dim),
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  for (final document in _Document.values) ...[
                    _Tab(
                      label: document.label,
                      selected: _showing == document,
                      onPressed: () => _show(document),
                    ),
                    const SizedBox(width: 6),
                  ],
                ],
              ),
              const SizedBox(height: 8),
              Expanded(child: _Reader(text: _text[_showing])),
              if (_linkFailure != null) ...[
                const SizedBox(height: 8),
                SelectableText(
                  'That page would not open. It is at $_linkFailure.',
                  style: const TextStyle(fontSize: 11, color: VdColors.warn),
                ),
              ],
            ],
          ),
        ),
        actions: [
          // Down here rather than beside the two tabs: three buttons in one
          // 560-wide row do not fit, and this one is an action on the sheet
          // where those two only choose what it is showing.
          TextButton(
            onPressed: () => unawaited(_openSource()),
            child: const Text('Get the source'),
          ),
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Close'),
          ),
        ],
      );
}

/// One of the two documents, or the moment before it has been read.
///
/// Selectable, because the whole point of a written offer is that somebody can
/// copy the address out of it.
class _Reader extends StatelessWidget {
  const _Reader({required this.text});

  final String? text;

  @override
  Widget build(BuildContext context) => Container(
        width: double.infinity,
        decoration: BoxDecoration(
          color: VdColors.rail,
          borderRadius: BorderRadius.circular(6),
          border: Border.all(color: VdColors.line),
        ),
        padding: const EdgeInsets.all(12),
        child: text == null
            // A word rather than a spinner: this is a file inside the app
            // bundle, and it is on screen for about one frame.
            ? const Text('Reading…',
                style: TextStyle(fontSize: 11, color: VdColors.dim))
            : SingleChildScrollView(
                child: SelectableText(
                  text!,
                  style: vdMono.copyWith(fontSize: 11, height: 1.35),
                ),
              ),
      );
}

class _Tab extends StatelessWidget {
  const _Tab({
    required this.label,
    required this.selected,
    required this.onPressed,
  });

  final String label;
  final bool selected;
  final VoidCallback onPressed;

  @override
  Widget build(BuildContext context) => selected
      ? FilledButton.tonal(onPressed: onPressed, child: Text(label))
      : TextButton(onPressed: onPressed, child: Text(label));
}
