/// The About sheet: which build this is, what is in it that we did not write,
/// and anything that has gone wrong on this machine.
///
/// It exists because of the second thing. FFmpeg is LGPL 2.1, and §6 asks for
/// prominent notice, a copy of the licence, and enough information to build a
/// replacement library and drop it in — obligations that are only discharged
/// if somebody running the app can actually reach them. A NOTICES file in a
/// repository is not that; neither is one in a disk image, which is a thing
/// people throw away the day they mount it. So the notice and the licence ship
/// as assets and this sheet shows both, verbatim.
///
/// It is also where the update story lives, such as it is. vdodtor has no
/// network entitlement and never checks for anything, so "Check for updates…"
/// opens the download page in the browser — see [About.download] for why that
/// is the arrangement rather than a missing feature.
///
/// And it is where a problem report is read, for the same reason and by the
/// same argument: nothing is uploaded, so the report has to be somewhere a
/// person can find it, and this is the sheet that already means "this
/// installation" rather than "this project". The tab only appears when there
/// is something in it — see `lib/app/crash.dart`.
///
/// Verbatim is the point. The notice is generated by `tools/make_notices.dart`
/// from the files actually vendored, and rendering it into prettier widgets
/// would make a second document that could disagree with the first about a
/// version number — which for a licence obligation is the one kind of drift
/// worse than a crash. The report is shown the same way and for a sharper
/// reason: the bytes on screen are the bytes somebody is about to paste into a
/// bug tracker, and a prettied rendering would be hiding some of them.
library;

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:vdodtor_engine/vdodtor_engine.dart';

import '../app/about.dart';
import '../app/crash.dart';
import 'theme.dart';

/// Which document the sheet is showing.
enum AboutTab {
  notices('Third-party notices'),
  licence('LGPL 2.1'),

  /// Only offered when there is at least one report. A permanently empty tab
  /// labelled "Problem reports" is a piece of furniture that makes the app
  /// look like it expects to crash.
  reports('Problem reports');

  const AboutTab(this.label);

  final String label;
}

/// Shows the sheet. Resolves when it is closed.
///
/// [reports] is optional because most callers have nothing to say about
/// crashes — the chooser's status line just wants the notices — and passing it
/// is what makes [AboutTab.reports] available at all.
Future<void> showAboutSheet(
  BuildContext context, {
  CrashReporter? reports,
  AboutTab initial = AboutTab.notices,
}) =>
    showDialog<void>(
      context: context,
      builder: (_) => _AboutSheet(reports: reports, initial: initial),
    );

class _AboutSheet extends StatefulWidget {
  const _AboutSheet({required this.reports, required this.initial});

  final CrashReporter? reports;
  final AboutTab initial;

  @override
  State<_AboutSheet> createState() => _AboutSheetState();
}

class _AboutSheetState extends State<_AboutSheet> {
  late AboutTab _showing;

  /// What each bundled document says, once it has been read. Kept for the life
  /// of the sheet rather than re-read on every tap of the selector, and
  /// dropped with it: see [About.read]. The reports are not in here — they are
  /// on disk, they are small, and one of them can be deleted while the sheet
  /// is open.
  final Map<AboutTab, String> _text = {};

  /// Set when a link could not be opened, on the licence sheet's terms: a
  /// button that silently does nothing is the one failure a user cannot
  /// report.
  String? _linkFailure;

  bool get _hasReports => (widget.reports?.count ?? 0) > 0;

  List<AboutTab> get _tabs => [
        AboutTab.notices,
        AboutTab.licence,
        if (_hasReports) AboutTab.reports,
      ];

  @override
  void initState() {
    super.initState();
    // Asking for the reports tab when there are none is not an error — the
    // banner that asks for it and the deletion that emptied it can happen in
    // either order — so it falls back rather than showing an empty box.
    _showing = _tabs.contains(widget.initial) ? widget.initial : _tabs.first;

    // Opening the sheet *is* being shown the report, so the offer stops here
    // rather than at the Dismiss button alone — but after the frame, not
    // during it. `initState` runs inside the build that pushes this route,
    // and the chooser's banner is an `AnimatedBuilder` listening to the same
    // notifier: telling it the offer is over while it is being built is
    // "setState() called during build" on the widget underneath the sheet.
    // The same hazard `CrashReporter.record` avoids by never notifying at
    // all, and it was the reporter's own first catch in the running app.
    if (_showing == AboutTab.reports) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (mounted) widget.reports?.markSeen();
      });
    }
    unawaited(_load(_showing));
  }

  Future<void> _load(AboutTab tab) async {
    final asset = switch (tab) {
      AboutTab.notices => About.noticesAsset,
      AboutTab.licence => About.licenceAsset,
      AboutTab.reports => null,
    };
    if (asset == null || _text.containsKey(tab)) return;
    final text = await About.read(asset);
    if (!mounted) return;
    setState(() => _text[tab] = text);
  }

  void _show(AboutTab tab) {
    setState(() => _showing = tab);
    if (tab == AboutTab.reports) widget.reports!.markSeen();
    unawaited(_load(tab));
  }

  /// Opens a page in the *browser*, which is the only way this app reaches
  /// anything: it has no network entitlement, so the asking is done by
  /// something that does. See [About.download].
  Future<void> _open(Uri url) async {
    final opened = await SystemLinks.open(url);
    if (!mounted || opened) return;
    setState(() => _linkFailure = url.toString());
  }

  /// Through [_show] rather than straight to `setState`: the tab it lands on
  /// may never have been read, because the banner can open this sheet on the
  /// reports tab and the notices are only fetched when they are asked for.
  void _deleteReports() {
    widget.reports!.deleteAll();
    _show(AboutTab.notices);
  }

  @override
  Widget build(BuildContext context) {
    final onReports = _showing == AboutTab.reports;
    return AlertDialog(
      backgroundColor: VdColors.panel,
      contentPadding: const EdgeInsets.fromLTRB(24, 20, 24, 8),
      content: SizedBox(
        width: 560,
        height: 460,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('vdodtor',
                style: TextStyle(
                  fontSize: 26,
                  fontWeight: FontWeight.w700,
                  letterSpacing: -0.8,
                )),
            const SizedBox(height: 2),
            // Selectable, because with no updater the version is a thing
            // people have to be able to read out and type into a bug report.
            const SelectableText(
              'Version ${About.version} · ${About.copyright}',
              style: TextStyle(fontSize: 11, color: VdColors.dim),
            ),
            const SizedBox(height: 14),
            // One paragraph or the other, never both: the sheet is a fixed
            // size because the reader inside it scrolls, so anything above the
            // reader that can grow has to be traded against something else.
            // They also say the same thing from two ends — no network, so no
            // updater and nothing sent when a fault happens — and the one to
            // show is the one about what is on screen underneath it.
            if (onReports) const _ReportPreamble() else const _Blurb(),
            const SizedBox(height: 16),
            // A [Wrap] rather than a [Row]: a third tab appeared here once
            // already, the labels are words rather than icons, and a selector
            // that overflows is one where the last tab cannot be reached at
            // all. Wrapping onto a second line costs the reader eight pixels
            // in the one case it happens.
            Wrap(
              spacing: 6,
              runSpacing: 6,
              children: [
                for (final tab in _tabs)
                  _Tab(
                    label: tab.label,
                    selected: _showing == tab,
                    onPressed: () => _show(tab),
                  ),
              ],
            ),
            const SizedBox(height: 8),
            Expanded(
              child: _Reader(
                text: onReports ? widget.reports!.text : _text[_showing],
              ),
            ),
            if (onReports) ...[
              const SizedBox(height: 8),
              _ReportActions(
                onCopy: () => unawaited(Clipboard.setData(
                    ClipboardData(text: widget.reports!.text))),
                onDelete: _deleteReports,
                onReport: () => unawaited(_open(About.bugs)),
              ),
            ],
            if (_linkFailure != null) ...[
              const SizedBox(height: 8),
              SelectableText(
                'That page would not open. It is at $_linkFailure.',
                style: const TextStyle(fontSize: 11, color: VdColors.warn),
              ),
            ],
          ],
        ),
      ),
      actions: [
        // Down here rather than beside the tabs: three buttons in one
        // 560-wide row do not fit, and these are actions on the sheet where
        // those only choose what it is showing.
        TextButton(
          onPressed: () => unawaited(_open(About.download)),
          child: const Text('Check for updates…'),
        ),
        TextButton(
          onPressed: () => unawaited(_open(About.source)),
          child: const Text('Get the source'),
        ),
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Close'),
        ),
      ],
    );
  }
}

/// What the app is, on the two tabs that are about the app.
///
/// The second sentence is said here rather than left to be discovered: an app
/// that never mentions a new version is unusual enough that silence reads as
/// an updater that is broken, and the reason it has none is the same sentence
/// as the reason nothing counts what you do.
class _Blurb extends StatelessWidget {
  const _Blurb();

  @override
  Widget build(BuildContext context) => const Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'A video editor with no watermark, no account and no ads. It has '
            'no network access at all: your footage never leaves this '
            'machine, because there is nowhere for it to go.',
            style: TextStyle(fontSize: 12, color: VdColors.dim),
          ),
          SizedBox(height: 10),
          Text(
            'So it never checks for updates, counts what you do, or reports '
            'anything when it goes wrong. New versions are announced on the '
            'website, and the button below opens it.',
            style: TextStyle(fontSize: 12, color: VdColors.dim),
          ),
        ],
      );
}

/// What the report is, before somebody reads one.
///
/// Two facts, and they are the two that decide what the user does next: it was
/// not collected, and it is theirs to send or delete. Without the first, a
/// crash log inside a privacy-first editor reads as the thing the pitch said
/// was not happening.
class _ReportPreamble extends StatelessWidget {
  const _ReportPreamble();

  @override
  Widget build(BuildContext context) => const Text(
        'Written on this machine and sent nowhere. File paths have been '
        'replaced with <path> before it was saved, so your footage is not '
        'named in it. Copy it into a bug report if you would like it looked '
        'at — a crash in the video engine itself is not in here, and lands in '
        'Console under Crash Reports.',
        style: TextStyle(fontSize: 11, color: VdColors.dim),
      );
}

class _ReportActions extends StatelessWidget {
  const _ReportActions({
    required this.onCopy,
    required this.onDelete,
    required this.onReport,
  });

  final VoidCallback onCopy;
  final VoidCallback onDelete;
  final VoidCallback onReport;

  @override
  Widget build(BuildContext context) => Row(
        children: [
          TextButton(onPressed: onCopy, child: const Text('Copy')),
          TextButton(onPressed: onDelete, child: const Text('Delete')),
          const Spacer(),
          FilledButton.tonal(
              onPressed: onReport, child: const Text('Report a bug…')),
        ],
      );
}

/// One of the documents, or the moment before it has been read.
///
/// Selectable, because the whole point of a written offer is that somebody can
/// copy the address out of it — and of a problem report that they can copy the
/// whole thing.
class _Reader extends StatelessWidget {
  const _Reader({required this.text});

  final String? text;

  @override
  Widget build(BuildContext context) => Container(
        width: double.infinity,
        decoration: BoxDecoration(
          color: VdColors.rail,
          borderRadius: BorderRadius.circular(6),
          border: Border.all(color: VdColors.line),
        ),
        padding: const EdgeInsets.all(12),
        child: text == null
            // A word rather than a spinner: this is a file inside the app
            // bundle, and it is on screen for about one frame.
            ? const Text('Reading…',
                style: TextStyle(fontSize: 11, color: VdColors.dim))
            : SingleChildScrollView(
                child: SelectableText(
                  text!,
                  style: vdMono.copyWith(fontSize: 11, height: 1.35),
                ),
              ),
      );
}

class _Tab extends StatelessWidget {
  const _Tab({
    required this.label,
    required this.selected,
    required this.onPressed,
  });

  final String label;
  final bool selected;
  final VoidCallback onPressed;

  @override
  Widget build(BuildContext context) => selected
      ? FilledButton.tonal(onPressed: onPressed, child: Text(label))
      : TextButton(onPressed: onPressed, child: Text(label));
}
