// What a look means, asserted on numbers.
//
// Everything here runs with no GPU, no window and no typeface — the bargain
// vd_color_test.c and vd_anim_test.c take, and the reason the arithmetic lives
// in vd_lut.c rather than in the shader. What is left in Metal is a texture
// fetch, and a test could tell you nothing about that.
//
// The last section reads the `.cube` files the app actually bundles. A look
// the tests pass with and the app does not ship is a look nothing checks —
// the same arrangement vd_text_test.c has with `assets/fonts`.

#include "vdodtor/vd_lut.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "vd_check.h"

#define VD_CHECK_NEAR(actual, expected, tolerance)                          \
  do {                                                                      \
    vd_checks++;                                                            \
    const double vd_a = (double)(actual);                                   \
    const double vd_e = (double)(expected);                                 \
    if (!(fabs(vd_a - vd_e) <= (double)(tolerance))) {                      \
      vd_failures++;                                                        \
      fprintf(stderr, "FAIL %s:%d: %s\n  expected %.6f +- %.6f\n"           \
                      "  actual   %.6f\n",                                  \
              __FILE__, __LINE__, #actual, vd_e, (double)(tolerance), vd_a); \
    }                                                                       \
  } while (0)

// --- writing test cubes ----------------------------------------------------

typedef void (*MapFn)(const float in[3], float out[3]);

// A `.cube` for `map`, sampled on an n-cube. Caller frees.
static char* cube_text(int n, MapFn map, const char* extra) {
  const size_t capacity = (size_t)n * n * n * 32 + 512;
  char* text = (char*)malloc(capacity);
  size_t at = 0;
  at += (size_t)snprintf(text + at, capacity - at,
                         "# generated by vd_lut_test\nTITLE \"Test\"\n"
                         "LUT_3D_SIZE %d\n%s",
                         n, extra ? extra : "");
  for (int b = 0; b < n; b++) {
    for (int g = 0; g < n; g++) {
      for (int r = 0; r < n; r++) {
        const float in[3] = {(float)r / (float)(n - 1),
                             (float)g / (float)(n - 1),
                             (float)b / (float)(n - 1)};
        float out[3];
        map(in, out);
        at += (size_t)snprintf(text + at, capacity - at, "%.6f %.6f %.6f\n",
                               out[0], out[1], out[2]);
      }
    }
  }
  return text;
}

static VdLut* parse_cube(int n, MapFn map, const char* extra) {
  char* text = cube_text(n, map, extra);
  VdLut* lut = vd_lut_parse(text, (int64_t)strlen(text), NULL);
  free(text);
  return lut;
}

static void map_identity(const float in[3], float out[3]) {
  out[0] = in[0];
  out[1] = in[1];
  out[2] = in[2];
}

// Swaps red and blue. Affine — a matrix could do it — which is exactly what
// makes it a good identity check for the plumbing: if the axis order were
// wrong, this would come back as something else entirely.
static void map_swap_rb(const float in[3], float out[3]) {
  out[0] = in[2];
  out[1] = in[1];
  out[2] = in[0];
}

// Shadows to blue, highlights to red, mids left alone. This one is *not*
// affine, and is the shape of every look worth having: the direction of the
// push depends on the value being pushed.
static void map_split(const float in[3], float out[3]) {
  const float l = 0.2126f * in[0] + 0.7152f * in[1] + 0.0722f * in[2];
  const float low = (1.0f - l) * (1.0f - l);
  const float high = l * l;
  out[0] = in[0] + 0.25f * high;
  out[1] = in[1];
  out[2] = in[2] + 0.25f * low;
  for (int i = 0; i < 3; i++) {
    if (out[i] < 0.0f) out[i] = 0.0f;
    if (out[i] > 1.0f) out[i] = 1.0f;
  }
}

static void sample(const VdLut* lut, float r, float g, float b, float out[3]) {
  out[0] = r;
  out[1] = g;
  out[2] = b;
  vd_lut_sample(lut, out);
}

// --- the parser ------------------------------------------------------------

static void test_identity(void) {
  VdLut* lut = parse_cube(2, map_identity, NULL);
  VD_CHECK(lut != NULL);
  if (!lut) return;

  VD_CHECK(vd_lut_is_3d(lut));
  VD_CHECK_EQ(vd_lut_size(lut), 2);
  VD_CHECK_STR(vd_lut_title(lut), "Test");

  // A 2-cube of the identity is the identity everywhere, because trilinear
  // between the eight corners of the colour cube *is* the colour cube.
  const float points[][3] = {
      {0, 0, 0}, {1, 1, 1}, {0.5f, 0.5f, 0.5f}, {0.25f, 0.7f, 0.1f}};
  for (size_t i = 0; i < sizeof(points) / sizeof(points[0]); i++) {
    float out[3];
    sample(lut, points[i][0], points[i][1], points[i][2], out);
    for (int ch = 0; ch < 3; ch++) VD_CHECK_NEAR(out[ch], points[i][ch], 1e-5);
  }
  vd_lut_close(lut);
}

// Red varies fastest, then green, then blue. Getting this backwards is the
// classic `.cube` bug and it looks like a plausible-but-wrong look rather than
// like a crash, so it is worth an assertion of its own.
static void test_axis_order(void) {
  VdLut* lut = parse_cube(3, map_swap_rb, NULL);
  VD_CHECK(lut != NULL);
  if (!lut) return;

  float out[3];
  sample(lut, 1, 0, 0, out);
  VD_CHECK_NEAR(out[0], 0.0f, 1e-5);
  VD_CHECK_NEAR(out[2], 1.0f, 1e-5);

  sample(lut, 0, 0, 1, out);
  VD_CHECK_NEAR(out[0], 1.0f, 1e-5);
  VD_CHECK_NEAR(out[2], 0.0f, 1e-5);

  // Green is the axis neither of the other two touched, so it has to come
  // through untouched as well.
  sample(lut, 0, 0.75f, 0, out);
  VD_CHECK_NEAR(out[1], 0.75f, 1e-5);
  vd_lut_close(lut);
}

// The lattice is only sampled *at* its points on the way in; everything the
// user sees is between them.
static void test_interpolates(void) {
  VdLut* lut = parse_cube(5, map_split, NULL);
  VD_CHECK(lut != NULL);
  if (!lut) return;

  // Halfway between two lattice points on a smooth map lands close to what the
  // formula says, which is what "trilinear" is worth.
  const float mid = 0.5f / 4.0f * 3.0f;  // 0.375: between the 2nd and 3rd point
  float expected[3];
  const float in[3] = {mid, mid, mid};
  map_split(in, expected);

  float out[3];
  sample(lut, mid, mid, mid, out);
  for (int ch = 0; ch < 3; ch++) VD_CHECK_NEAR(out[ch], expected[ch], 0.01);

  // The two ends are lattice points, so they are exact rather than close.
  float black[3];
  map_split((const float[]){0, 0, 0}, black);
  sample(lut, 0, 0, 0, out);
  for (int ch = 0; ch < 3; ch++) VD_CHECK_NEAR(out[ch], black[ch], 1e-5);

  float white[3];
  map_split((const float[]){1, 1, 1}, white);
  sample(lut, 1, 1, 1, out);
  for (int ch = 0; ch < 3; ch++) VD_CHECK_NEAR(out[ch], white[ch], 1e-5);
  vd_lut_close(lut);
}

// A look is not a matrix, and this is the assertion that says so: no 3x3 and
// offset can send both ends of the ramp in opposite directions on one channel.
static void test_not_affine(void) {
  VdLut* lut = parse_cube(9, map_split, NULL);
  VD_CHECK(lut != NULL);
  if (!lut) return;

  float shadow[3];
  float highlight[3];
  sample(lut, 0.1f, 0.1f, 0.1f, shadow);
  sample(lut, 0.9f, 0.9f, 0.9f, highlight);

  // Blue rises in the shadows and red rises in the highlights. Under any
  // affine map, a step along the grey axis moves every channel by the same
  // amount whichever end of the axis it is taken from.
  VD_CHECK(shadow[2] - 0.1f > 0.1f);
  VD_CHECK(highlight[2] - 0.9f < 0.02f);
  VD_CHECK(highlight[0] - 0.9f > 0.05f);
  VD_CHECK(shadow[0] - 0.1f < 0.02f);
  vd_lut_close(lut);
}

static void test_comments_and_whitespace(void) {
  const char* text =
      "\r\n"
      "# a comment\r\n"
      "   # an indented comment\r\n"
      "TITLE \"Spaced Out\"\r\n"
      "\r\n"
      "LUT_3D_SIZE 2\r\n"
      "LUT_1D_INPUT_RANGE_SOMETHING_NEW 0 1\r\n"  // a keyword from the future
      "0 0 0\r\n"
      "  1 0 0  \r\n"
      "0 1 0\r\n"
      "1 1 0\r\n"
      "0 0 1\r\n"
      "1 0 1\r\n"
      "0 1 1\r\n"
      "1 1 1\r\n";
  int32_t result = -99;
  VdLut* lut = vd_lut_parse(text, (int64_t)strlen(text), &result);
  VD_CHECK(lut != NULL);
  VD_CHECK_EQ(result, 0);
  if (!lut) return;
  VD_CHECK_STR(vd_lut_title(lut), "Spaced Out");
  float out[3];
  sample(lut, 0.3f, 0.6f, 0.9f, out);
  VD_CHECK_NEAR(out[0], 0.3f, 1e-5);
  VD_CHECK_NEAR(out[1], 0.6f, 1e-5);
  VD_CHECK_NEAR(out[2], 0.9f, 1e-5);
  vd_lut_close(lut);
}

// The reason vd_lut.c parses its own decimals instead of calling strtof: under
// a locale whose separator is a comma, strtof reads "0.5" as 0 and every look
// loads without error and renders as garbage. A test that ran under the C
// locale would not catch that, so what is asserted here is the parser's own
// reach — signs, exponents, a bare leading point — rather than the locale.
static void test_number_forms(void) {
  const char* text =
      "LUT_3D_SIZE 2\n"
      "0 0 0\n"
      "1e0 0 0\n"
      ".5 0 0\n"
      "5.0E-1 0 0\n"
      "+0.0 1 0\n"
      "1.000000 1 0\n"
      "0 0 1\n"
      "1 0 1\n";
  VdLut* lut = vd_lut_parse(text, (int64_t)strlen(text), NULL);
  VD_CHECK(lut != NULL);
  if (!lut) return;
  // Each corner of the 2-cube is one row, in the order red varies fastest, so
  // reading a corner reads exactly one of the spellings above.
  float out[3];
  sample(lut, 1, 0, 0, out);  // row 2: "1e0"
  VD_CHECK_NEAR(out[0], 1.0f, 1e-5);
  sample(lut, 0, 1, 0, out);  // row 3: ".5", a bare leading point
  VD_CHECK_NEAR(out[0], 0.5f, 1e-5);
  sample(lut, 1, 1, 0, out);  // row 4: "5.0E-1", a capital exponent
  VD_CHECK_NEAR(out[0], 0.5f, 1e-5);
  sample(lut, 0, 0, 1, out);  // row 5: "+0.0", a leading plus
  VD_CHECK_NEAR(out[0], 0.0f, 1e-5);
  VD_CHECK_NEAR(out[1], 1.0f, 1e-5);
  vd_lut_close(lut);
}

// A one-dimensional file is three curves, and nothing a channel does can
// affect another. That is the whole difference from a cube.
static void test_one_dimensional(void) {
  const char* text =
      "TITLE Uncoted Title\n"
      "LUT_1D_SIZE 3\n"
      "0.0 0.0 0.0\n"
      "0.25 0.5 0.75\n"
      "1.0 1.0 1.0\n";
  VdLut* lut = vd_lut_parse(text, (int64_t)strlen(text), NULL);
  VD_CHECK(lut != NULL);
  if (!lut) return;
  VD_CHECK(!vd_lut_is_3d(lut));
  VD_CHECK_EQ(vd_lut_size(lut), 3);
  // A TITLE with no quotes is common enough in the wild to accept.
  VD_CHECK_STR(vd_lut_title(lut), "Uncoted Title");

  float out[3];
  sample(lut, 0.5f, 0.5f, 0.5f, out);
  VD_CHECK_NEAR(out[0], 0.25f, 1e-5);
  VD_CHECK_NEAR(out[1], 0.5f, 1e-5);
  VD_CHECK_NEAR(out[2], 0.75f, 1e-5);

  // Red's curve must not care what green and blue are doing.
  float other[3];
  sample(lut, 0.5f, 0.0f, 1.0f, other);
  VD_CHECK_NEAR(other[0], 0.25f, 1e-5);

  // A curve is baked into a cube on the way to the GPU, because a cube is the
  // only shape a 3D texture has.
  VD_CHECK_EQ(vd_lut_bake_size(lut), 33);
  const VdColorLook look = vd_lut_look(lut, 1.0f);
  VD_CHECK_EQ(look.size, 33);
  VD_CHECK(look.lattice != NULL);
  vd_lut_close(lut);
}

// The cube the compositor samples has to say what the sampler says, or the
// numbers this file asserts are numbers nobody sees.
static void test_bake_matches_sample(void) {
  VdLut* lut = parse_cube(5, map_split, NULL);
  VD_CHECK(lut != NULL);
  if (!lut) return;

  // A 3D file over the default domain *is* the cube already — same size, same
  // order, same values — so the bake is the parsed table and not a copy of it.
  VD_CHECK_EQ(vd_lut_bake_size(lut), 5);
  const VdColorLook look = vd_lut_look(lut, 1.0f);
  VD_CHECK_EQ(look.size, 5);
  VD_CHECK(look.id != 0);
  VD_CHECK_NEAR(look.strength, 1.0f, 1e-6);

  for (int b = 0; b < 5; b++) {
    for (int g = 0; g < 5; g++) {
      for (int r = 0; r < 5; r++) {
        float expected[3];
        sample(lut, (float)r / 4.0f, (float)g / 4.0f, (float)b / 4.0f,
               expected);
        const int index = ((b * 5) + g) * 5 + r;
        for (int ch = 0; ch < 3; ch++) {
          VD_CHECK_NEAR(look.lattice[index * 3 + ch], expected[ch], 1e-5);
        }
      }
    }
  }
  vd_lut_close(lut);
}

// A curve baked into 33 points is an approximation, and this says how good.
static void test_bake_of_a_curve(void) {
  const int n = 256;
  const size_t capacity = (size_t)n * 32 + 128;
  char* text = (char*)malloc(capacity);
  size_t at = (size_t)snprintf(text, capacity, "LUT_1D_SIZE %d\n", n);
  for (int i = 0; i < n; i++) {
    const double v = (double)i / (double)(n - 1);
    at += (size_t)snprintf(text + at, capacity - at, "%.6f %.6f %.6f\n", v * v,
                           v * v, v * v);
  }
  VdLut* lut = vd_lut_parse(text, (int64_t)at, NULL);
  free(text);
  VD_CHECK(lut != NULL);
  if (!lut) return;

  const VdColorLook look = vd_lut_look(lut, 1.0f);
  VD_CHECK_EQ(look.size, 33);
  // Reading the baked cube the way the GPU does — trilinear between the two
  // nearest points on the grey axis — against the curve it came from.
  for (int i = 0; i <= 20; i++) {
    const float v = (float)i / 20.0f;
    const float scaled = v * 32.0f;
    int lower = (int)scaled;
    if (lower > 31) lower = 31;
    const float f = scaled - (float)lower;
    const int64_t a = ((int64_t)lower * 33 + lower) * 33 + lower;
    const int64_t b = ((int64_t)(lower + 1) * 33 + lower + 1) * 33 + lower + 1;
    const float baked =
        look.lattice[a * 3] + (look.lattice[b * 3] - look.lattice[a * 3]) * f;
    VD_CHECK_NEAR(baked, v * v, 0.001);
  }
  vd_lut_close(lut);
}

// A file that says its lattice covers 0..2 is describing a different map from
// the same numbers, and reading it as 0..1 would halve every look.
static void test_domain(void) {
  const char* text =
      "LUT_3D_SIZE 2\n"
      "DOMAIN_MIN 0.0 0.0 0.0\n"
      "DOMAIN_MAX 2.0 2.0 2.0\n"
      "0 0 0\n1 0 0\n0 1 0\n1 1 0\n0 0 1\n1 0 1\n0 1 1\n1 1 1\n";
  VdLut* lut = vd_lut_parse(text, (int64_t)strlen(text), NULL);
  VD_CHECK(lut != NULL);
  if (!lut) return;

  // Input 1.0 is halfway along a lattice that runs to 2.0, so it reads the
  // middle of the ramp.
  float out[3];
  sample(lut, 1, 1, 1, out);
  for (int ch = 0; ch < 3; ch++) VD_CHECK_NEAR(out[ch], 0.5f, 1e-5);

  // And the bake is a real resampling here rather than an alias, because the
  // cube the GPU samples is always over 0..1.
  const VdColorLook look = vd_lut_look(lut, 1.0f);
  VD_CHECK_EQ(look.size, 2);
  // The far corner of the baked cube is input 1.0, which the file maps to 0.5.
  VD_CHECK_NEAR(look.lattice[(2 * 2 * 2 - 1) * 3], 0.5f, 1e-5);
  vd_lut_close(lut);
}

// The format permits values outside 0..1 for log looks. This is a
// display-referred pipeline with nowhere to put them, and — more to the point
// — the GPU's normalised texture clamps them on upload, so clamping here is
// what keeps this file's numbers and the screen's agreeing.
static void test_clamps_out_of_range(void) {
  const char* text =
      "LUT_3D_SIZE 2\n"
      "-0.5 0 0\n2.0 0 0\n0 -1 0\n1 2 0\n0 0 0\n1 0 0\n0 1 0\n1 1 1.5\n";
  VdLut* lut = vd_lut_parse(text, (int64_t)strlen(text), NULL);
  VD_CHECK(lut != NULL);
  if (!lut) return;
  float out[3];
  sample(lut, 0, 0, 0, out);
  VD_CHECK_NEAR(out[0], 0.0f, 1e-6);
  sample(lut, 1, 0, 0, out);
  VD_CHECK_NEAR(out[0], 1.0f, 1e-6);
  sample(lut, 1, 1, 1, out);
  VD_CHECK_NEAR(out[2], 1.0f, 1e-6);
  vd_lut_close(lut);
}

static void test_rejects_bad_files(void) {
  struct {
    const char* what;
    const char* text;
  } cases[] = {
      {"no size line", "0 0 0\n1 1 1\n"},
      {"data before the size", "0 0 0\nLUT_3D_SIZE 2\n"},
      {"too few rows", "LUT_3D_SIZE 2\n0 0 0\n1 1 1\n"},
      {"too many rows",
       "LUT_3D_SIZE 2\n0 0 0\n1 0 0\n0 1 0\n1 1 0\n0 0 1\n1 0 1\n0 1 1\n"
       "1 1 1\n0.5 0.5 0.5\n"},
      {"a one-point lattice", "LUT_3D_SIZE 1\n0 0 0\n"},
      {"a lattice past the ceiling", "LUT_3D_SIZE 128\n0 0 0\n"},
      {"two size lines", "LUT_3D_SIZE 2\nLUT_1D_SIZE 3\n0 0 0\n"},
      {"a size that is not a number", "LUT_3D_SIZE big\n0 0 0\n"},
      {"an inside-out domain",
       "LUT_3D_SIZE 2\nDOMAIN_MIN 1 1 1\nDOMAIN_MAX 0 0 0\n"
       "0 0 0\n1 0 0\n0 1 0\n1 1 0\n0 0 1\n1 0 1\n0 1 1\n1 1 1\n"},
      {"nothing at all", "\n\n# just comments\n"},
  };
  for (size_t i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
    int32_t result = 0;
    VdLut* lut =
        vd_lut_parse(cases[i].text, (int64_t)strlen(cases[i].text), &result);
    if (lut) {
      vd_failures++;
      fprintf(stderr, "FAIL %s:%d: accepted %s\n", __FILE__, __LINE__,
              cases[i].what);
      vd_lut_close(lut);
    }
    vd_checks++;
    VD_CHECK(result < 0);
  }

  VD_CHECK(vd_lut_parse(NULL, 10, NULL) == NULL);
  VD_CHECK(vd_lut_parse("x", 0, NULL) == NULL);
  VD_CHECK(vd_lut_open("/nonexistent/nowhere.cube", NULL) == NULL);
}

// --- strength --------------------------------------------------------------

static void test_strength(void) {
  VdLut* lut = parse_cube(3, map_split, NULL);
  VD_CHECK(lut != NULL);
  if (!lut) return;

  float full[3];
  sample(lut, 0.2f, 0.2f, 0.2f, full);

  float none[3] = {0.2f, 0.2f, 0.2f};
  vd_lut_apply(lut, 0.0f, none);
  for (int ch = 0; ch < 3; ch++) VD_CHECK_NEAR(none[ch], 0.2f, 1e-6);

  float all[3] = {0.2f, 0.2f, 0.2f};
  vd_lut_apply(lut, 1.0f, all);
  for (int ch = 0; ch < 3; ch++) VD_CHECK_NEAR(all[ch], full[ch], 1e-6);

  // Halfway is halfway, on every channel — which is what makes one strength
  // slider work for a monochrome and for a split-tone alike.
  float half[3] = {0.2f, 0.2f, 0.2f};
  vd_lut_apply(lut, 0.5f, half);
  for (int ch = 0; ch < 3; ch++) {
    VD_CHECK_NEAR(half[ch], 0.2f + (full[ch] - 0.2f) * 0.5f, 1e-6);
  }

  // Out of range is clamped rather than believed.
  float over[3] = {0.2f, 0.2f, 0.2f};
  vd_lut_apply(lut, 4.0f, over);
  for (int ch = 0; ch < 3; ch++) VD_CHECK_NEAR(over[ch], full[ch], 1e-6);

  // A look at no strength is no look at all, so the compositor never uploads a
  // cube for a slider somebody dragged to zero.
  const VdColorLook silent = vd_lut_look(lut, 0.0f);
  VD_CHECK_EQ(silent.size, 0);
  VD_CHECK(silent.lattice == NULL);

  // And no look is what a clip with none on it hands over.
  const VdColorLook nothing = vd_lut_look(NULL, 1.0f);
  VD_CHECK_EQ(nothing.size, 0);
  VD_CHECK_EQ((int64_t)nothing.id, 0);
  vd_lut_close(lut);
}

// The compositor keys its texture cache on the id, so two looks must never
// share one — a cube freed and another allocated at the same address would be
// a cache hit on the wrong picture.
static void test_ids_are_distinct(void) {
  VdLut* a = parse_cube(2, map_identity, NULL);
  VdLut* b = parse_cube(2, map_identity, NULL);
  VD_CHECK(a != NULL && b != NULL);
  if (!a || !b) return;
  const VdColorLook look_a = vd_lut_look(a, 1.0f);
  const VdColorLook look_b = vd_lut_look(b, 1.0f);
  VD_CHECK(look_a.id != 0);
  VD_CHECK(look_a.id != look_b.id);
  // The same look asked twice is the same id, or every frame would look like a
  // new cube to the cache.
  VD_CHECK(vd_lut_look(a, 0.5f).id == look_a.id);
  vd_lut_close(a);
  vd_lut_close(b);
}

// --- the catalogue ---------------------------------------------------------

static void test_catalogue(void) {
  char* text = cube_text(2, map_swap_rb, NULL);
  const int32_t before = vd_lut_count();

  VD_CHECK_EQ(vd_lut_register("Swap", text, (int64_t)strlen(text)), 0);
  VD_CHECK_EQ(vd_lut_count(), before + 1);
  VD_CHECK_STR(vd_lut_name(before), "Swap");

  const VdLut* found = vd_lut_find("Swap");
  VD_CHECK(found != NULL);
  if (found) {
    float out[3];
    sample(found, 1, 0, 0, out);
    VD_CHECK_NEAR(out[2], 1.0f, 1e-5);
  }

  // Registering a name that is already there is what happens on a hot restart.
  // It is not an error, and it must not swap the cube out from under every
  // clip already pointing at it.
  VD_CHECK_EQ(vd_lut_register("Swap", text, (int64_t)strlen(text)), 0);
  VD_CHECK_EQ(vd_lut_count(), before + 1);
  VD_CHECK(vd_lut_find("Swap") == found);

  // A name nothing was registered under draws ungraded rather than failing —
  // the bargain a caption in a missing face already takes.
  VD_CHECK(vd_lut_find("Nothing Like It") == NULL);
  VD_CHECK(vd_lut_find("") == NULL);
  VD_CHECK(vd_lut_find(NULL) == NULL);
  VD_CHECK_STR(vd_lut_name(-1), "");
  VD_CHECK_STR(vd_lut_name(9999), "");

  VD_CHECK(vd_lut_register(NULL, text, 4) < 0);
  VD_CHECK(vd_lut_register("Bad", NULL, 4) < 0);
  VD_CHECK(vd_lut_register("Bad", text, 0) < 0);
  // A file that is not a look is refused rather than registered empty.
  VD_CHECK(vd_lut_register("Not A Look", "hello", 5) < 0);
  free(text);
}

// --- the looks the app ships -----------------------------------------------

static void test_bundled_looks(void) {
  // Every one of these is named in app/lib/media/looks.dart and generated by
  // tools/make_luts.dart. A look the app offers and the engine cannot read is
  // a filter that does nothing when it is clicked.
  const char* files[] = {"warm_film.cube", "noir.cube", "teal_orange.cube",
                         "faded.cube", "bleach_bypass.cube"};

  for (size_t i = 0; i < sizeof(files) / sizeof(files[0]); i++) {
    char path[512];
    snprintf(path, sizeof(path), "%s/%s", VD_LUT_DIR, files[i]);
    int32_t result = -99;
    VdLut* lut = vd_lut_open(path, &result);
    if (!lut) {
      vd_failures++;
      vd_checks++;
      fprintf(stderr, "FAIL %s:%d: %s did not open (%d)\n", __FILE__, __LINE__,
              path, result);
      continue;
    }
    VD_CHECK(vd_lut_is_3d(lut));
    VD_CHECK_EQ(vd_lut_size(lut), 17);

    // A look moves the picture. One that came back as the identity would be a
    // filter that does nothing, and it would look exactly like a bug in the
    // shader rather than like a bug in the file.
    //
    // Asked across the range rather than at one colour, because mid-grey is
    // precisely where these do the least: an S-curve pivots there and a
    // split-tone's weights vanish there, so a probe at 50% would call the
    // gentlest of them broken while it was working exactly as written.
    const float probes[][3] = {{0.1f, 0.1f, 0.1f},
                               {0.5f, 0.45f, 0.4f},
                               {0.9f, 0.9f, 0.9f},
                               {0.8f, 0.3f, 0.2f},
                               {0.2f, 0.3f, 0.8f}};
    float furthest = 0.0f;
    for (size_t p = 0; p < sizeof(probes) / sizeof(probes[0]); p++) {
      float out[3];
      sample(lut, probes[p][0], probes[p][1], probes[p][2], out);
      float distance = 0.0f;
      for (int ch = 0; ch < 3; ch++) {
        distance += fabsf(out[ch] - probes[p][ch]);
      }
      if (distance > furthest) furthest = distance;
    }
    VD_CHECK(furthest > 0.05f);

    // And it stays a picture: black near black, white near white. A look that
    // sent either end somewhere else would be a colour cast, not a grade.
    float black[3];
    float white[3];
    sample(lut, 0, 0, 0, black);
    sample(lut, 1, 1, 1, white);
    for (int ch = 0; ch < 3; ch++) {
      VD_CHECK(black[ch] < 0.2f);
      VD_CHECK(white[ch] > 0.8f);
    }
    vd_lut_close(lut);
  }

  // Noir is the one that has to be monochrome, and it is the only one where
  // that is checkable rather than a matter of taste.
  char path[512];
  snprintf(path, sizeof(path), "%s/noir.cube", VD_LUT_DIR);
  VdLut* noir = vd_lut_open(path, NULL);
  VD_CHECK(noir != NULL);
  if (noir) {
    const float colours[][3] = {
        {0.9f, 0.1f, 0.1f}, {0.1f, 0.9f, 0.1f}, {0.1f, 0.1f, 0.9f}};
    for (size_t i = 0; i < 3; i++) {
      float out[3];
      sample(noir, colours[i][0], colours[i][1], colours[i][2], out);
      VD_CHECK_NEAR(out[0], out[1], 0.03);
      VD_CHECK_NEAR(out[1], out[2], 0.03);
    }
    vd_lut_close(noir);
  }
}

int main(void) {
  test_identity();
  test_axis_order();
  test_interpolates();
  test_not_affine();
  test_comments_and_whitespace();
  test_number_forms();
  test_one_dimensional();
  test_bake_matches_sample();
  test_bake_of_a_curve();
  test_domain();
  test_clamps_out_of_range();
  test_rejects_bad_files();
  test_strength();
  test_ids_are_distinct();
  test_catalogue();
  test_bundled_looks();
  return VD_REPORT();
}
