// GENERATED FILE — do not edit.
// Regenerate with: dart run ffigen --config ffigen.yaml
// ignore_for_file: always_specify_types, camel_case_types
// ignore_for_file: non_constant_identifier_names, unused_element

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Generated bindings for the vdodtor native engine.
///
/// Source of truth: engine/include/vdodtor/*.h
/// Regenerate with `dart run ffigen --config ffigen.yaml`.
///
class VdEngineBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  VdEngineBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  VdEngineBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// value * mul / div, rounded half away from zero, reduced before multiplying
  /// so a long timeline cannot overflow.
  int vd_scale(int value, int mul, int div) {
    return _vd_scale(value, mul, div);
  }

  late final _vd_scalePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int64 Function(ffi.Int64, ffi.Int64, ffi.Int64)>
      >('vd_scale');
  late final _vd_scale = _vd_scalePtr.asFunction<int Function(int, int, int)>();

  /// Exact ticks per frame at `fps`, or 0 if the timebase cannot represent it.
  /// A 0 return is a programming error at the caller, not a rounding hint.
  int vd_ticks_per_frame(VdRational fps) {
    return _vd_ticks_per_frame(fps);
  }

  late final _vd_ticks_per_framePtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(VdRational)>>(
        'vd_ticks_per_frame',
      );
  late final _vd_ticks_per_frame = _vd_ticks_per_framePtr
      .asFunction<int Function(VdRational)>();

  bool vd_timebase_divides(VdRational fps) {
    return _vd_timebase_divides(fps);
  }

  late final _vd_timebase_dividesPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(VdRational)>>(
        'vd_timebase_divides',
      );
  late final _vd_timebase_divides = _vd_timebase_dividesPtr
      .asFunction<bool Function(VdRational)>();

  int vd_ticks_from_nanos(int nanos) {
    return _vd_ticks_from_nanos(nanos);
  }

  late final _vd_ticks_from_nanosPtr =
      _lookup<ffi.NativeFunction<VdTick Function(ffi.Int64)>>(
        'vd_ticks_from_nanos',
      );
  late final _vd_ticks_from_nanos = _vd_ticks_from_nanosPtr
      .asFunction<int Function(int)>();

  int vd_nanos_from_ticks(int ticks) {
    return _vd_nanos_from_ticks(ticks);
  }

  late final _vd_nanos_from_ticksPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(VdTick)>>(
        'vd_nanos_from_ticks',
      );
  late final _vd_nanos_from_ticks = _vd_nanos_from_ticksPtr
      .asFunction<int Function(int)>();

  /// Converts a timestamp on a stream's own timebase (as FFmpeg reports it,
  /// e.g. 1/90000) into project ticks.
  int vd_ticks_from_stream_time(int pts, VdRational timebase) {
    return _vd_ticks_from_stream_time(pts, timebase);
  }

  late final _vd_ticks_from_stream_timePtr =
      _lookup<ffi.NativeFunction<VdTick Function(ffi.Int64, VdRational)>>(
        'vd_ticks_from_stream_time',
      );
  late final _vd_ticks_from_stream_time = _vd_ticks_from_stream_timePtr
      .asFunction<int Function(int, VdRational)>();

  int vd_stream_time_from_ticks(int ticks, VdRational timebase) {
    return _vd_stream_time_from_ticks(ticks, timebase);
  }

  late final _vd_stream_time_from_ticksPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(VdTick, VdRational)>>(
        'vd_stream_time_from_ticks',
      );
  late final _vd_stream_time_from_ticks = _vd_stream_time_from_ticksPtr
      .asFunction<int Function(int, VdRational)>();

  /// Frame index containing `t`, flooring so it is stable across the whole frame.
  int vd_frame_of_tick(int t, VdRational fps) {
    return _vd_frame_of_tick(t, fps);
  }

  late final _vd_frame_of_tickPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(VdTick, VdRational)>>(
        'vd_frame_of_tick',
      );
  late final _vd_frame_of_tick = _vd_frame_of_tickPtr
      .asFunction<int Function(int, VdRational)>();

  int vd_tick_of_frame(int frame, VdRational fps) {
    return _vd_tick_of_frame(frame, fps);
  }

  late final _vd_tick_of_framePtr =
      _lookup<ffi.NativeFunction<VdTick Function(ffi.Int64, VdRational)>>(
        'vd_tick_of_frame',
      );
  late final _vd_tick_of_frame = _vd_tick_of_framePtr
      .asFunction<int Function(int, VdRational)>();

  /// A clip at rest: the identity for every field. Not a zeroed struct — a zeroed
  /// one is invisible, unscaled and empty, which is what a clip looks like
  /// *before* it arrives rather than after.
  VdAnimValue vd_anim_rest() {
    return _vd_anim_rest();
  }

  late final _vd_anim_restPtr =
      _lookup<ffi.NativeFunction<VdAnimValue Function()>>('vd_anim_rest');
  late final _vd_anim_rest = _vd_anim_restPtr
      .asFunction<VdAnimValue Function()>();

  /// One preset at `t`, where 0 is fully away and 1 is at rest.
  ///
  /// The easing lives in here rather than in a curve the caller picks, because a
  /// preset is a whole gesture: "pop" is the overshoot as much as it is the
  /// scale, and letting the two be chosen separately would offer a thousand
  /// combinations to get one of them right.
  ///
  /// `t` outside 0..1 is clamped, so a caller doing its own arithmetic on ticks
  /// cannot produce a frame nobody designed.
  VdAnimValue vd_anim_value(VdAnimPreset preset, double t) {
    return _vd_anim_value(preset.value, t);
  }

  late final _vd_anim_valuePtr =
      _lookup<
        ffi.NativeFunction<VdAnimValue Function(ffi.UnsignedInt, ffi.Float)>
      >('vd_anim_value');
  late final _vd_anim_value = _vd_anim_valuePtr
      .asFunction<VdAnimValue Function(int, double)>();

  /// A clip nobody has animated.
  VdClipAnim vd_clip_anim_none() {
    return _vd_clip_anim_none();
  }

  late final _vd_clip_anim_nonePtr =
      _lookup<ffi.NativeFunction<VdClipAnim Function()>>('vd_clip_anim_none');
  late final _vd_clip_anim_none = _vd_clip_anim_nonePtr
      .asFunction<VdClipAnim Function()>();

  /// Where a clip is `offset` ticks into a `duration`-long life.
  ///
  /// Works out which half applies and evaluates it. When both halves reach the
  /// same instant — a clip shorter than its own animations — the one that is
  /// *further from rest* wins rather than the two being combined: composing two
  /// entrances produces a motion neither preset describes, and the more extreme
  /// of the two is the one somebody asked for.
  VdAnimValue vd_anim_at(
    ffi.Pointer<VdClipAnim> anim,
    int offset,
    int duration,
  ) {
    return _vd_anim_at(anim, offset, duration);
  }

  late final _vd_anim_atPtr =
      _lookup<
        ffi.NativeFunction<
          VdAnimValue Function(ffi.Pointer<VdClipAnim>, VdTick, VdTick)
        >
      >('vd_anim_at');
  late final _vd_anim_at = _vd_anim_atPtr
      .asFunction<VdAnimValue Function(ffi.Pointer<VdClipAnim>, int, int)>();

  /// True when nothing about this animation would change a frame. The engine uses
  /// it to keep a caption's raster: a clip whose animation is only ever transform
  /// and opacity never needs re-drawing, and one with a typewriter on it does.
  bool vd_anim_reveals_text(ffi.Pointer<VdClipAnim> anim) {
    return _vd_anim_reveals_text(anim);
  }

  late final _vd_anim_reveals_textPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<VdClipAnim>)>>(
        'vd_anim_reveals_text',
      );
  late final _vd_anim_reveals_text = _vd_anim_reveals_textPtr
      .asFunction<bool Function(ffi.Pointer<VdClipAnim>)>();

  /// Fills `out` from `path`. Returns VD_OK, or a negative VdResult.
  /// Never partially fills: on failure `out` is zeroed.
  int vd_probe_file(ffi.Pointer<ffi.Char> path, ffi.Pointer<VdProbeInfo> out) {
    return _vd_probe_file(path, out);
  }

  late final _vd_probe_filePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<VdProbeInfo>)
        >
      >('vd_probe_file');
  late final _vd_probe_file = _vd_probe_filePtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<VdProbeInfo>)
      >();

  /// Human-readable form of a VdResult, for logs and error surfaces.
  ffi.Pointer<ffi.Char> vd_result_string(int result) {
    return _vd_result_string(result);
  }

  late final _vd_result_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int32)>>(
        'vd_result_string',
      );
  late final _vd_result_string = _vd_result_stringPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  VdDecoderOptions vd_decoder_default_options() {
    return _vd_decoder_default_options();
  }

  late final _vd_decoder_default_optionsPtr =
      _lookup<ffi.NativeFunction<VdDecoderOptions Function()>>(
        'vd_decoder_default_options',
      );
  late final _vd_decoder_default_options = _vd_decoder_default_optionsPtr
      .asFunction<VdDecoderOptions Function()>();

  /// Opens `path` for decoding. `out_result` receives VD_OK or a negative
  /// VdResult; it may be NULL. Returns NULL on failure.
  ffi.Pointer<VdDecoder> vd_decoder_open(
    ffi.Pointer<ffi.Char> path,
    VdDecoderOptions options,
    ffi.Pointer<ffi.Int32> out_result,
  ) {
    return _vd_decoder_open(path, options, out_result);
  }

  late final _vd_decoder_openPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VdDecoder> Function(
            ffi.Pointer<ffi.Char>,
            VdDecoderOptions,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('vd_decoder_open');
  late final _vd_decoder_open = _vd_decoder_openPtr
      .asFunction<
        ffi.Pointer<VdDecoder> Function(
          ffi.Pointer<ffi.Char>,
          VdDecoderOptions,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  void vd_decoder_close(ffi.Pointer<VdDecoder> decoder) {
    return _vd_decoder_close(decoder);
  }

  late final _vd_decoder_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdDecoder>)>>(
        'vd_decoder_close',
      );
  late final _vd_decoder_close = _vd_decoder_closePtr
      .asFunction<void Function(ffi.Pointer<VdDecoder>)>();

  /// What probing the same file would have said. Free — it is read at open.
  int vd_decoder_info(
    ffi.Pointer<VdDecoder> decoder,
    ffi.Pointer<VdProbeInfo> out,
  ) {
    return _vd_decoder_info(decoder, out);
  }

  late final _vd_decoder_infoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<VdDecoder>, ffi.Pointer<VdProbeInfo>)
        >
      >('vd_decoder_info');
  late final _vd_decoder_info = _vd_decoder_infoPtr
      .asFunction<
        int Function(ffi.Pointer<VdDecoder>, ffi.Pointer<VdProbeInfo>)
      >();

  /// The frame whose presentation interval contains `t`.
  ///
  /// Clamps: a `t` before the first frame returns the first, and a `t` past the
  /// end returns the last. That is what a timeline wants — a clip trimmed a tick
  /// past its source should show the last frame, not a black hole.
  ///
  /// Returns VD_OK, or VD_ERR_DECODE if the file has no decodable video.
  int vd_decoder_frame_at(
    ffi.Pointer<VdDecoder> decoder,
    int t,
    ffi.Pointer<VdFrame> out,
  ) {
    return _vd_decoder_frame_at(decoder, t, out);
  }

  late final _vd_decoder_frame_atPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VdDecoder>,
            VdTick,
            ffi.Pointer<VdFrame>,
          )
        >
      >('vd_decoder_frame_at');
  late final _vd_decoder_frame_at = _vd_decoder_frame_atPtr
      .asFunction<
        int Function(ffi.Pointer<VdDecoder>, int, ffi.Pointer<VdFrame>)
      >();

  /// Releases the frame's buffer and zeroes it. Safe on an already-released or
  /// zeroed frame.
  void vd_frame_release(ffi.Pointer<VdFrame> frame) {
    return _vd_frame_release(frame);
  }

  late final _vd_frame_releasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdFrame>)>>(
        'vd_frame_release',
      );
  late final _vd_frame_release = _vd_frame_releasePtr
      .asFunction<void Function(ffi.Pointer<VdFrame>)>();

  /// --- keyframe index --------------------------------------------------------
  /// Built at open from the container's index. Seeking anywhere means landing on
  /// one of these and decoding forward, so the distance between them is the real
  /// cost of a scrub.
  int vd_decoder_keyframe_count(ffi.Pointer<VdDecoder> decoder) {
    return _vd_decoder_keyframe_count(decoder);
  }

  late final _vd_decoder_keyframe_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<VdDecoder>)>>(
        'vd_decoder_keyframe_count',
      );
  late final _vd_decoder_keyframe_count = _vd_decoder_keyframe_countPtr
      .asFunction<int Function(ffi.Pointer<VdDecoder>)>();

  /// The latest keyframe at or before `t`, or 0 when the container has no index.
  int vd_decoder_keyframe_at_or_before(ffi.Pointer<VdDecoder> decoder, int t) {
    return _vd_decoder_keyframe_at_or_before(decoder, t);
  }

  late final _vd_decoder_keyframe_at_or_beforePtr =
      _lookup<
        ffi.NativeFunction<VdTick Function(ffi.Pointer<VdDecoder>, VdTick)>
      >('vd_decoder_keyframe_at_or_before');
  late final _vd_decoder_keyframe_at_or_before =
      _vd_decoder_keyframe_at_or_beforePtr
          .asFunction<int Function(ffi.Pointer<VdDecoder>, int)>();

  void vd_decoder_stats(
    ffi.Pointer<VdDecoder> decoder,
    ffi.Pointer<VdDecoderStats> out,
  ) {
    return _vd_decoder_stats(decoder, out);
  }

  late final _vd_decoder_statsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<VdDecoder>, ffi.Pointer<VdDecoderStats>)
        >
      >('vd_decoder_stats');
  late final _vd_decoder_stats = _vd_decoder_statsPtr
      .asFunction<
        void Function(ffi.Pointer<VdDecoder>, ffi.Pointer<VdDecoderStats>)
      >();

  void vd_decoder_reset_stats(ffi.Pointer<VdDecoder> decoder) {
    return _vd_decoder_reset_stats(decoder);
  }

  late final _vd_decoder_reset_statsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdDecoder>)>>(
        'vd_decoder_reset_stats',
      );
  late final _vd_decoder_reset_stats = _vd_decoder_reset_statsPtr
      .asFunction<void Function(ffi.Pointer<VdDecoder>)>();

  /// The identity, spelled out. Equivalent to a zeroed struct; this exists so
  /// callers can say what they mean.
  VdTransform vd_transform_identity() {
    return _vd_transform_identity();
  }

  late final _vd_transform_identityPtr =
      _lookup<ffi.NativeFunction<VdTransform Function()>>(
        'vd_transform_identity',
      );
  late final _vd_transform_identity = _vd_transform_identityPtr
      .asFunction<VdTransform Function()>();

  /// Creates a compositor rendering `width` x `height` BGRA frames.
  /// `out_result` may be NULL.
  ffi.Pointer<VdCompositor> vd_compositor_create(
    int width,
    int height,
    ffi.Pointer<ffi.Int32> out_result,
  ) {
    return _vd_compositor_create(width, height, out_result);
  }

  late final _vd_compositor_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VdCompositor> Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('vd_compositor_create');
  late final _vd_compositor_create = _vd_compositor_createPtr
      .asFunction<
        ffi.Pointer<VdCompositor> Function(int, int, ffi.Pointer<ffi.Int32>)
      >();

  void vd_compositor_destroy(ffi.Pointer<VdCompositor> compositor) {
    return _vd_compositor_destroy(compositor);
  }

  late final _vd_compositor_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdCompositor>)>>(
        'vd_compositor_destroy',
      );
  late final _vd_compositor_destroy = _vd_compositor_destroyPtr
      .asFunction<void Function(ffi.Pointer<VdCompositor>)>();

  int vd_compositor_width(ffi.Pointer<VdCompositor> compositor) {
    return _vd_compositor_width(compositor);
  }

  late final _vd_compositor_widthPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<VdCompositor>)>
      >('vd_compositor_width');
  late final _vd_compositor_width = _vd_compositor_widthPtr
      .asFunction<int Function(ffi.Pointer<VdCompositor>)>();

  int vd_compositor_height(ffi.Pointer<VdCompositor> compositor) {
    return _vd_compositor_height(compositor);
  }

  late final _vd_compositor_heightPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<VdCompositor>)>
      >('vd_compositor_height');
  late final _vd_compositor_height = _vd_compositor_heightPtr
      .asFunction<int Function(ffi.Pointer<VdCompositor>)>();

  /// Composites `layers` bottom-to-top onto black and publishes the result.
  /// Blocks until the GPU is done, so the frame is ready to hand to Flutter or an
  /// encoder the moment this returns.
  int vd_compositor_render(
    ffi.Pointer<VdCompositor> compositor,
    ffi.Pointer<VdLayer> layers,
    int layer_count,
  ) {
    return _vd_compositor_render(compositor, layers, layer_count);
  }

  late final _vd_compositor_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VdCompositor>,
            ffi.Pointer<VdLayer>,
            ffi.Int32,
          )
        >
      >('vd_compositor_render');
  late final _vd_compositor_render = _vd_compositor_renderPtr
      .asFunction<
        int Function(ffi.Pointer<VdCompositor>, ffi.Pointer<VdLayer>, int)
      >();

  /// The most recent composited frame, retained. Caller releases with
  /// CVPixelBufferRelease. NULL before the first render.
  ffi.Pointer<ffi.Void> vd_compositor_copy_output(
    ffi.Pointer<VdCompositor> compositor,
  ) {
    return _vd_compositor_copy_output(compositor);
  }

  late final _vd_compositor_copy_outputPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<VdCompositor>)
        >
      >('vd_compositor_copy_output');
  late final _vd_compositor_copy_output = _vd_compositor_copy_outputPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<VdCompositor>)>();

  /// Milliseconds of GPU time the last render took.
  double vd_compositor_last_gpu_ms(ffi.Pointer<VdCompositor> compositor) {
    return _vd_compositor_last_gpu_ms(compositor);
  }

  late final _vd_compositor_last_gpu_msPtr =
      _lookup<
        ffi.NativeFunction<ffi.Double Function(ffi.Pointer<VdCompositor>)>
      >('vd_compositor_last_gpu_ms');
  late final _vd_compositor_last_gpu_ms = _vd_compositor_last_gpu_msPtr
      .asFunction<double Function(ffi.Pointer<VdCompositor>)>();

  /// Writes the last composited frame to `path` as PNG. This is how the
  /// compositor gets checked on pixels rather than on timings.
  int vd_compositor_dump_png(
    ffi.Pointer<VdCompositor> compositor,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _vd_compositor_dump_png(compositor, path);
  }

  late final _vd_compositor_dump_pngPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<VdCompositor>, ffi.Pointer<ffi.Char>)
        >
      >('vd_compositor_dump_png');
  late final _vd_compositor_dump_png = _vd_compositor_dump_pngPtr
      .asFunction<
        int Function(ffi.Pointer<VdCompositor>, ffi.Pointer<ffi.Char>)
      >();

  /// Reads one pixel of the last composited frame, as 8-bit BGRA. Out of range
  /// returns false. For tests: an assertion on colour is worth more than an
  /// assertion on frame count.
  bool vd_compositor_read_pixel(
    ffi.Pointer<VdCompositor> compositor,
    int x,
    int y,
    ffi.Pointer<ffi.Uint8> out_bgra,
  ) {
    return _vd_compositor_read_pixel(compositor, x, y, out_bgra);
  }

  late final _vd_compositor_read_pixelPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<VdCompositor>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Uint8>,
          )
        >
      >('vd_compositor_read_pixel');
  late final _vd_compositor_read_pixel = _vd_compositor_read_pixelPtr
      .asFunction<
        bool Function(
          ffi.Pointer<VdCompositor>,
          int,
          int,
          ffi.Pointer<ffi.Uint8>,
        )
      >();

  /// Copies the last composited frame into `out` as tightly packed BGRA —
  /// width * height * 4 bytes, no row padding. The output buffer the GPU writes
  /// into is padded to a stride of its own choosing, and every consumer outside
  /// this file (Flutter's decodeImageFromPixels, an encoder, a PNG writer) wants
  /// it packed, so the unpacking happens once, here.
  ///
  /// Returns VD_ERR_INVALID_ARG if `capacity` is short of that. A compositor
  /// that has not rendered yet copies out black, the same thing it would show.
  int vd_compositor_copy_pixels(
    ffi.Pointer<VdCompositor> compositor,
    ffi.Pointer<ffi.Uint8> out,
    int capacity,
  ) {
    return _vd_compositor_copy_pixels(compositor, out, capacity);
  }

  late final _vd_compositor_copy_pixelsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VdCompositor>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int64,
          )
        >
      >('vd_compositor_copy_pixels');
  late final _vd_compositor_copy_pixels = _vd_compositor_copy_pixelsPtr
      .asFunction<
        int Function(ffi.Pointer<VdCompositor>, ffi.Pointer<ffi.Uint8>, int)
      >();

  /// A shape with nothing said about it: an opaque white rectangle, unstroked,
  /// unshadowed, square-cornered, big enough to see. Not a zeroed struct — a
  /// zeroed one is a transparent shape with no size, which is not a default
  /// anybody wants.
  VdShapeSpec vd_shape_spec_default() {
    return _vd_shape_spec_default();
  }

  late final _vd_shape_spec_defaultPtr =
      _lookup<ffi.NativeFunction<VdShapeSpec Function()>>(
        'vd_shape_spec_default',
      );
  late final _vd_shape_spec_default = _vd_shape_spec_defaultPtr
      .asFunction<VdShapeSpec Function()>();

  /// True when two specs would rasterise to the same pixels. Field by field
  /// rather than a memcmp: a struct with a mix of enums and floats has padding
  /// in it, and padding is whatever was on the stack.
  ///
  /// The fields a kind ignores are compared anyway. A rectangle's `head_size`
  /// cannot change its pixels, so calling two rectangles different over it costs
  /// one redraw of one shape on the edit that changed it — where getting the
  /// exception wrong the other way round would leave a stale raster on screen.
  bool vd_shape_spec_equal(
    ffi.Pointer<VdShapeSpec> a,
    ffi.Pointer<VdShapeSpec> b,
  ) {
    return _vd_shape_spec_equal(a, b);
  }

  late final _vd_shape_spec_equalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<VdShapeSpec>, ffi.Pointer<VdShapeSpec>)
        >
      >('vd_shape_spec_equal');
  late final _vd_shape_spec_equal = _vd_shape_spec_equalPtr
      .asFunction<
        bool Function(ffi.Pointer<VdShapeSpec>, ffi.Pointer<VdShapeSpec>)
      >();

  /// A heap copy, and the matching free. The engine holds a spec for as long as
  /// a clip is on the timeline; the caller that handed it over keeps its own.
  /// Both accept NULL, which is a clip that is not a shape.
  ffi.Pointer<VdShapeSpec> vd_shape_spec_copy(ffi.Pointer<VdShapeSpec> spec) {
    return _vd_shape_spec_copy(spec);
  }

  late final _vd_shape_spec_copyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VdShapeSpec> Function(ffi.Pointer<VdShapeSpec>)
        >
      >('vd_shape_spec_copy');
  late final _vd_shape_spec_copy = _vd_shape_spec_copyPtr
      .asFunction<
        ffi.Pointer<VdShapeSpec> Function(ffi.Pointer<VdShapeSpec>)
      >();

  void vd_shape_spec_free(ffi.Pointer<VdShapeSpec> spec) {
    return _vd_shape_spec_free(spec);
  }

  late final _vd_shape_spec_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdShapeSpec>)>>(
        'vd_shape_spec_free',
      );
  late final _vd_shape_spec_free = _vd_shape_spec_freePtr
      .asFunction<void Function(ffi.Pointer<VdShapeSpec>)>();

  /// Rasterises `spec` into a new `width` x `height` CVPixelBufferRef: 32BGRA,
  /// **premultiplied**, transparent everywhere the shape is not. IOSurface-backed
  /// and Metal-compatible, so the compositor wraps it without a copy.
  ///
  /// The box is centred in the frame; moving it is the clip transform's job, not
  /// this function's. Caller releases with CVPixelBufferRelease. NULL on failure,
  /// with `out_result` — which may be NULL — set to a negative VdResult.
  ffi.Pointer<ffi.Void> vd_shape_render(
    ffi.Pointer<VdShapeSpec> spec,
    int width,
    int height,
    ffi.Pointer<ffi.Int32> out_result,
  ) {
    return _vd_shape_render(spec, width, height, out_result);
  }

  late final _vd_shape_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<VdShapeSpec>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('vd_shape_render');
  late final _vd_shape_render = _vd_shape_renderPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<VdShapeSpec>,
          int,
          int,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  /// A caption with nothing said about it: white, unstroked, unboxed, centred,
  /// at a readable size. Not a zeroed struct — a zeroed one is transparent type
  /// with no size, which is not a default anybody wants.
  VdTextSpec vd_text_spec_default() {
    return _vd_text_spec_default();
  }

  late final _vd_text_spec_defaultPtr =
      _lookup<ffi.NativeFunction<VdTextSpec Function()>>(
        'vd_text_spec_default',
      );
  late final _vd_text_spec_default = _vd_text_spec_defaultPtr
      .asFunction<VdTextSpec Function()>();

  /// True when two specs would rasterise to the same pixels. This is what lets
  /// the engine keep a raster across an edit that did not touch the text.
  bool vd_text_spec_equal(
    ffi.Pointer<VdTextSpec> a,
    ffi.Pointer<VdTextSpec> b,
  ) {
    return _vd_text_spec_equal(a, b);
  }

  late final _vd_text_spec_equalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<VdTextSpec>, ffi.Pointer<VdTextSpec>)
        >
      >('vd_text_spec_equal');
  late final _vd_text_spec_equal = _vd_text_spec_equalPtr
      .asFunction<
        bool Function(ffi.Pointer<VdTextSpec>, ffi.Pointer<VdTextSpec>)
      >();

  /// A copy that owns its own strings, and the matching free. The engine holds a
  /// spec for as long as a clip is on the timeline; the caller that handed it
  /// over keeps its own.
  ffi.Pointer<VdTextSpec> vd_text_spec_copy(ffi.Pointer<VdTextSpec> spec) {
    return _vd_text_spec_copy(spec);
  }

  late final _vd_text_spec_copyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VdTextSpec> Function(ffi.Pointer<VdTextSpec>)
        >
      >('vd_text_spec_copy');
  late final _vd_text_spec_copy = _vd_text_spec_copyPtr
      .asFunction<ffi.Pointer<VdTextSpec> Function(ffi.Pointer<VdTextSpec>)>();

  void vd_text_spec_free(ffi.Pointer<VdTextSpec> spec) {
    return _vd_text_spec_free(spec);
  }

  late final _vd_text_spec_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdTextSpec>)>>(
        'vd_text_spec_free',
      );
  late final _vd_text_spec_free = _vd_text_spec_freePtr
      .asFunction<void Function(ffi.Pointer<VdTextSpec>)>();

  /// Registers a font from memory, for this process only. `data` is the contents
  /// of a .ttf or .otf; it is copied, so the caller may free it on return.
  ///
  /// Bytes rather than a path because the fonts ship inside the app bundle, where
  /// the only address anybody has for them is an asset key. Registering the same
  /// face twice is not an error — it is what happens when the app restarts an
  /// engine — and the second registration is quietly ignored.
  int vd_text_register_font(ffi.Pointer<ffi.Void> data, int size) {
    return _vd_text_register_font(data, size);
  }

  late final _vd_text_register_fontPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Int64)>
      >('vd_text_register_font');
  late final _vd_text_register_font = _vd_text_register_fontPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, int)>();

  /// The families registered so far, in the order they arrived. For tests and for
  /// telling a UI what it may offer.
  int vd_text_font_count() {
    return _vd_text_font_count();
  }

  late final _vd_text_font_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>('vd_text_font_count');
  late final _vd_text_font_count = _vd_text_font_countPtr
      .asFunction<int Function()>();

  ffi.Pointer<ffi.Char> vd_text_font_name(int index) {
    return _vd_text_font_name(index);
  }

  late final _vd_text_font_namePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int32)>>(
        'vd_text_font_name',
      );
  late final _vd_text_font_name = _vd_text_font_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  /// How many characters `spec` would draw, counted the way a person counts
  /// them: composed characters, so an accent or a flag is one and not two or
  /// four. This is what a typewriter animation divides its time by.
  int vd_text_length(ffi.Pointer<VdTextSpec> spec) {
    return _vd_text_length(spec);
  }

  late final _vd_text_lengthPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<VdTextSpec>)>>(
        'vd_text_length',
      );
  late final _vd_text_length = _vd_text_lengthPtr
      .asFunction<int Function(ffi.Pointer<VdTextSpec>)>();

  /// Rasterises `spec` into a new `width` x `height` CVPixelBufferRef: 32BGRA,
  /// **premultiplied**, transparent everywhere the ink is not. IOSurface-backed
  /// and Metal-compatible, so the compositor wraps it without a copy.
  ///
  /// `reveal` draws only the first that many composed characters; negative draws
  /// all of them, and 0 draws nothing. It is a parameter rather than a field on
  /// the spec on purpose: the spec is what the *document* says a caption looks
  /// like, and how much of it has been typed so far is a fact about the playhead.
  /// Keeping them apart is what lets vd_text_spec_equal stay a comparison of two
  /// documents.
  ///
  /// Wrapping is computed on the whole string rather than on the prefix, so a
  /// caption that will wrap does not reflow underneath the typewriter as it
  /// arrives — the words that are already on screen have to stay where they are.
  ///
  /// The block is laid out centred in the frame; moving it is the clip
  /// transform's job, not this function's. Caller releases with
  /// CVPixelBufferRelease. NULL on failure, with `out_result` — which may be
  /// NULL — set to a negative VdResult.
  ffi.Pointer<ffi.Void> vd_text_render(
    ffi.Pointer<VdTextSpec> spec,
    int width,
    int height,
    int reveal,
    ffi.Pointer<ffi.Int32> out_result,
  ) {
    return _vd_text_render(spec, width, height, reveal, out_result);
  }

  late final _vd_text_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<VdTextSpec>,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('vd_text_render');
  late final _vd_text_render = _vd_text_renderPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<VdTextSpec>,
          int,
          int,
          int,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  /// A clip with nothing said about it: fully opaque, full volume, contained,
  /// carrying a picture, and with no volume line — for which a zeroed pointer and
  /// count happen to be exactly right.
  ///
  /// Worth the four lines it costs. Unlike VdTransform, this struct cannot make a
  /// zeroed value mean "no opinion" — gain 0 is silence and opacity 0 is
  /// invisible, and both are things a caller might legitimately ask for, so
  /// neither can double as "unset". A caller that memsets and fills in three
  /// fields would get a silent, invisible clip, which is a bug that looks like
  /// nothing happening at all.
  VdTimelineClip vd_timeline_clip_default() {
    return _vd_timeline_clip_default();
  }

  late final _vd_timeline_clip_defaultPtr =
      _lookup<ffi.NativeFunction<VdTimelineClip Function()>>(
        'vd_timeline_clip_default',
      );
  late final _vd_timeline_clip_default = _vd_timeline_clip_defaultPtr
      .asFunction<VdTimelineClip Function()>();

  VdEngineOptions vd_engine_default_options() {
    return _vd_engine_default_options();
  }

  late final _vd_engine_default_optionsPtr =
      _lookup<ffi.NativeFunction<VdEngineOptions Function()>>(
        'vd_engine_default_options',
      );
  late final _vd_engine_default_options = _vd_engine_default_optionsPtr
      .asFunction<VdEngineOptions Function()>();

  ffi.Pointer<VdEngine> vd_engine_create(ffi.Pointer<ffi.Int32> out_result) {
    return _vd_engine_create(out_result);
  }

  late final _vd_engine_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VdEngine> Function(ffi.Pointer<ffi.Int32>)
        >
      >('vd_engine_create');
  late final _vd_engine_create = _vd_engine_createPtr
      .asFunction<ffi.Pointer<VdEngine> Function(ffi.Pointer<ffi.Int32>)>();

  ffi.Pointer<VdEngine> vd_engine_create_with_options(
    VdEngineOptions options,
    ffi.Pointer<ffi.Int32> out_result,
  ) {
    return _vd_engine_create_with_options(options, out_result);
  }

  late final _vd_engine_create_with_optionsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VdEngine> Function(
            VdEngineOptions,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('vd_engine_create_with_options');
  late final _vd_engine_create_with_options = _vd_engine_create_with_optionsPtr
      .asFunction<
        ffi.Pointer<VdEngine> Function(VdEngineOptions, ffi.Pointer<ffi.Int32>)
      >();

  /// The engine's audio renderer, for pulling frames when no device is attached.
  /// Owned by the engine; valid until vd_engine_destroy.
  ffi.Pointer<VdAudioRenderer> vd_engine_audio_renderer(
    ffi.Pointer<VdEngine> engine,
  ) {
    return _vd_engine_audio_renderer(engine);
  }

  late final _vd_engine_audio_rendererPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VdAudioRenderer> Function(ffi.Pointer<VdEngine>)
        >
      >('vd_engine_audio_renderer');
  late final _vd_engine_audio_renderer = _vd_engine_audio_rendererPtr
      .asFunction<
        ffi.Pointer<VdAudioRenderer> Function(ffi.Pointer<VdEngine>)
      >();

  /// Stops the render thread, waits for it, and only then tears anything down.
  /// The S1 spike freed the engine while GPU completion handlers still held it,
  /// and it presented as gradual slowdown rather than a crash.
  void vd_engine_destroy(ffi.Pointer<VdEngine> engine) {
    return _vd_engine_destroy(engine);
  }

  late final _vd_engine_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdEngine>)>>(
        'vd_engine_destroy',
      );
  late final _vd_engine_destroy = _vd_engine_destroyPtr
      .asFunction<void Function(ffi.Pointer<VdEngine>)>();

  /// Replaces the render list. Safe to call while playing: the current position
  /// is kept, and the next rendered frame reflects the new timeline. Reopening
  /// decoders is avoided where a clip's source is unchanged.
  int vd_engine_set_timeline(
    ffi.Pointer<VdEngine> engine,
    ffi.Pointer<VdTimeline> timeline,
  ) {
    return _vd_engine_set_timeline(engine, timeline);
  }

  late final _vd_engine_set_timelinePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<VdEngine>, ffi.Pointer<VdTimeline>)
        >
      >('vd_engine_set_timeline');
  late final _vd_engine_set_timeline = _vd_engine_set_timelinePtr
      .asFunction<
        int Function(ffi.Pointer<VdEngine>, ffi.Pointer<VdTimeline>)
      >();

  void vd_engine_play(ffi.Pointer<VdEngine> engine) {
    return _vd_engine_play(engine);
  }

  late final _vd_engine_playPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdEngine>)>>(
        'vd_engine_play',
      );
  late final _vd_engine_play = _vd_engine_playPtr
      .asFunction<void Function(ffi.Pointer<VdEngine>)>();

  void vd_engine_pause(ffi.Pointer<VdEngine> engine) {
    return _vd_engine_pause(engine);
  }

  late final _vd_engine_pausePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdEngine>)>>(
        'vd_engine_pause',
      );
  late final _vd_engine_pause = _vd_engine_pausePtr
      .asFunction<void Function(ffi.Pointer<VdEngine>)>();

  /// Moves the playhead. Renders one frame even when paused, which is what makes
  /// scrubbing show anything.
  void vd_engine_seek(ffi.Pointer<VdEngine> engine, int position) {
    return _vd_engine_seek(engine, position);
  }

  late final _vd_engine_seekPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdEngine>, VdTick)>
      >('vd_engine_seek');
  late final _vd_engine_seek = _vd_engine_seekPtr
      .asFunction<void Function(ffi.Pointer<VdEngine>, int)>();

  /// Renders the current position once, synchronously, on the calling thread.
  /// For tests and for the first frame after a timeline change.
  int vd_engine_render_now(ffi.Pointer<VdEngine> engine) {
    return _vd_engine_render_now(engine);
  }

  late final _vd_engine_render_nowPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<VdEngine>)>>(
        'vd_engine_render_now',
      );
  late final _vd_engine_render_now = _vd_engine_render_nowPtr
      .asFunction<int Function(ffi.Pointer<VdEngine>)>();

  int vd_engine_position(ffi.Pointer<VdEngine> engine) {
    return _vd_engine_position(engine);
  }

  late final _vd_engine_positionPtr =
      _lookup<ffi.NativeFunction<VdTick Function(ffi.Pointer<VdEngine>)>>(
        'vd_engine_position',
      );
  late final _vd_engine_position = _vd_engine_positionPtr
      .asFunction<int Function(ffi.Pointer<VdEngine>)>();

  int vd_engine_duration(ffi.Pointer<VdEngine> engine) {
    return _vd_engine_duration(engine);
  }

  late final _vd_engine_durationPtr =
      _lookup<ffi.NativeFunction<VdTick Function(ffi.Pointer<VdEngine>)>>(
        'vd_engine_duration',
      );
  late final _vd_engine_duration = _vd_engine_durationPtr
      .asFunction<int Function(ffi.Pointer<VdEngine>)>();

  int vd_engine_state(ffi.Pointer<VdEngine> engine) {
    return _vd_engine_state(engine);
  }

  late final _vd_engine_statePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<VdEngine>)>>(
        'vd_engine_state',
      );
  late final _vd_engine_state = _vd_engine_statePtr
      .asFunction<int Function(ffi.Pointer<VdEngine>)>();

  void vd_engine_set_frame_callback(
    ffi.Pointer<VdEngine> engine,
    VdFrameCallback callback,
    ffi.Pointer<ffi.Void> context,
  ) {
    return _vd_engine_set_frame_callback(engine, callback, context);
  }

  late final _vd_engine_set_frame_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<VdEngine>,
            VdFrameCallback,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('vd_engine_set_frame_callback');
  late final _vd_engine_set_frame_callback = _vd_engine_set_frame_callbackPtr
      .asFunction<
        void Function(
          ffi.Pointer<VdEngine>,
          VdFrameCallback,
          ffi.Pointer<ffi.Void>,
        )
      >();

  /// The most recently published frame as a CVPixelBufferRef, retained. NULL
  /// before the first render. Caller releases.
  ffi.Pointer<ffi.Void> vd_engine_copy_output(ffi.Pointer<VdEngine> engine) {
    return _vd_engine_copy_output(engine);
  }

  late final _vd_engine_copy_outputPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<VdEngine>)
        >
      >('vd_engine_copy_output');
  late final _vd_engine_copy_output = _vd_engine_copy_outputPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<VdEngine>)>();

  /// Writes the last published frame to `path` as PNG.
  int vd_engine_dump_png(
    ffi.Pointer<VdEngine> engine,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _vd_engine_dump_png(engine, path);
  }

  late final _vd_engine_dump_pngPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<VdEngine>, ffi.Pointer<ffi.Char>)
        >
      >('vd_engine_dump_png');
  late final _vd_engine_dump_png = _vd_engine_dump_pngPtr
      .asFunction<int Function(ffi.Pointer<VdEngine>, ffi.Pointer<ffi.Char>)>();

  void vd_engine_stats(
    ffi.Pointer<VdEngine> engine,
    ffi.Pointer<VdEngineStats> out,
  ) {
    return _vd_engine_stats(engine, out);
  }

  late final _vd_engine_statsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<VdEngine>, ffi.Pointer<VdEngineStats>)
        >
      >('vd_engine_stats');
  late final _vd_engine_stats = _vd_engine_statsPtr
      .asFunction<
        void Function(ffi.Pointer<VdEngine>, ffi.Pointer<VdEngineStats>)
      >();

  /// Renders the frame covering `t` in `path`, scaled to fit inside
  /// `max_width` x `max_height`.
  ///
  /// The result carries the source's *display* aspect — rotation and sample
  /// aspect already applied — and is not letterboxed, so a caller can lay it out
  /// without knowing anything about the file. Both dimensions come back even,
  /// and at least 2.
  ///
  /// Returns VD_OK, or a negative VdResult: VD_ERR_INVALID_ARG for the arguments,
  /// VD_ERR_OPEN for a file that will not open, VD_ERR_UNSUPPORTED for one with
  /// no video stream — which is where an audio file lands, and is a fact about
  /// the file rather than a failure — and VD_ERR_DECODE when there is a video
  /// stream but no frame came out of it. `out` is zeroed on every failure.
  int vd_thumbnail_render(
    ffi.Pointer<ffi.Char> path,
    int t,
    int max_width,
    int max_height,
    ffi.Pointer<VdThumbnail> out,
  ) {
    return _vd_thumbnail_render(path, t, max_width, max_height, out);
  }

  late final _vd_thumbnail_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Char>,
            VdTick,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<VdThumbnail>,
          )
        >
      >('vd_thumbnail_render');
  late final _vd_thumbnail_render = _vd_thumbnail_renderPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          int,
          int,
          int,
          ffi.Pointer<VdThumbnail>,
        )
      >();

  /// Frees the pixels and zeroes the struct. Safe on a zeroed thumbnail, and
  /// safe twice.
  void vd_thumbnail_free(ffi.Pointer<VdThumbnail> thumb) {
    return _vd_thumbnail_free(thumb);
  }

  late final _vd_thumbnail_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdThumbnail>)>>(
        'vd_thumbnail_free',
      );
  late final _vd_thumbnail_free = _vd_thumbnail_freePtr
      .asFunction<void Function(ffi.Pointer<VdThumbnail>)>();

  /// Opens the audio stream of `path`. Returns NULL and sets `out_result` when
  /// there is no audio to decode — which is not an error the caller should treat
  /// as fatal, since plenty of video has no sound.
  ffi.Pointer<VdAudioSource> vd_audio_source_open(
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Int32> out_result,
  ) {
    return _vd_audio_source_open(path, out_result);
  }

  late final _vd_audio_source_openPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VdAudioSource> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('vd_audio_source_open');
  late final _vd_audio_source_open = _vd_audio_source_openPtr
      .asFunction<
        ffi.Pointer<VdAudioSource> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  void vd_audio_source_close(ffi.Pointer<VdAudioSource> source) {
    return _vd_audio_source_close(source);
  }

  late final _vd_audio_source_closePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdAudioSource>)>
      >('vd_audio_source_close');
  late final _vd_audio_source_close = _vd_audio_source_closePtr
      .asFunction<void Function(ffi.Pointer<VdAudioSource>)>();

  /// Moves to `source_time` in the file. The next read starts there.
  int vd_audio_source_seek(ffi.Pointer<VdAudioSource> source, int source_time) {
    return _vd_audio_source_seek(source, source_time);
  }

  late final _vd_audio_source_seekPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<VdAudioSource>, VdTick)
        >
      >('vd_audio_source_seek');
  late final _vd_audio_source_seek = _vd_audio_source_seekPtr
      .asFunction<int Function(ffi.Pointer<VdAudioSource>, int)>();

  /// Reads up to `frames` interleaved stereo float frames. Returns the number
  /// actually written; fewer than asked for means the source ended.
  int vd_audio_source_read(
    ffi.Pointer<VdAudioSource> source,
    ffi.Pointer<ffi.Float> out,
    int frames,
  ) {
    return _vd_audio_source_read(source, out, frames);
  }

  late final _vd_audio_source_readPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VdAudioSource>,
            ffi.Pointer<ffi.Float>,
            ffi.Int32,
          )
        >
      >('vd_audio_source_read');
  late final _vd_audio_source_read = _vd_audio_source_readPtr
      .asFunction<
        int Function(ffi.Pointer<VdAudioSource>, ffi.Pointer<ffi.Float>, int)
      >();

  /// Source time of the next frame that will be read.
  int vd_audio_source_position(ffi.Pointer<VdAudioSource> source) {
    return _vd_audio_source_position(source);
  }

  late final _vd_audio_source_positionPtr =
      _lookup<ffi.NativeFunction<VdTick Function(ffi.Pointer<VdAudioSource>)>>(
        'vd_audio_source_position',
      );
  late final _vd_audio_source_position = _vd_audio_source_positionPtr
      .asFunction<int Function(ffi.Pointer<VdAudioSource>)>();

  int vd_audio_source_duration(ffi.Pointer<VdAudioSource> source) {
    return _vd_audio_source_duration(source);
  }

  late final _vd_audio_source_durationPtr =
      _lookup<ffi.NativeFunction<VdTick Function(ffi.Pointer<VdAudioSource>)>>(
        'vd_audio_source_duration',
      );
  late final _vd_audio_source_duration = _vd_audio_source_durationPtr
      .asFunction<int Function(ffi.Pointer<VdAudioSource>)>();

  ffi.Pointer<VdAudioRing> vd_audio_ring_create(int capacity_frames) {
    return _vd_audio_ring_create(capacity_frames);
  }

  late final _vd_audio_ring_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<VdAudioRing> Function(ffi.Int32)>>(
        'vd_audio_ring_create',
      );
  late final _vd_audio_ring_create = _vd_audio_ring_createPtr
      .asFunction<ffi.Pointer<VdAudioRing> Function(int)>();

  void vd_audio_ring_destroy(ffi.Pointer<VdAudioRing> ring) {
    return _vd_audio_ring_destroy(ring);
  }

  late final _vd_audio_ring_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdAudioRing>)>>(
        'vd_audio_ring_destroy',
      );
  late final _vd_audio_ring_destroy = _vd_audio_ring_destroyPtr
      .asFunction<void Function(ffi.Pointer<VdAudioRing>)>();

  /// Producer side. Returns frames actually written.
  int vd_audio_ring_write(
    ffi.Pointer<VdAudioRing> ring,
    ffi.Pointer<ffi.Float> frames,
    int count,
  ) {
    return _vd_audio_ring_write(ring, frames, count);
  }

  late final _vd_audio_ring_writePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VdAudioRing>,
            ffi.Pointer<ffi.Float>,
            ffi.Int32,
          )
        >
      >('vd_audio_ring_write');
  late final _vd_audio_ring_write = _vd_audio_ring_writePtr
      .asFunction<
        int Function(ffi.Pointer<VdAudioRing>, ffi.Pointer<ffi.Float>, int)
      >();

  /// Consumer side. Returns frames actually read; the rest of `out` is untouched.
  int vd_audio_ring_read(
    ffi.Pointer<VdAudioRing> ring,
    ffi.Pointer<ffi.Float> out,
    int count,
  ) {
    return _vd_audio_ring_read(ring, out, count);
  }

  late final _vd_audio_ring_readPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VdAudioRing>,
            ffi.Pointer<ffi.Float>,
            ffi.Int32,
          )
        >
      >('vd_audio_ring_read');
  late final _vd_audio_ring_read = _vd_audio_ring_readPtr
      .asFunction<
        int Function(ffi.Pointer<VdAudioRing>, ffi.Pointer<ffi.Float>, int)
      >();

  int vd_audio_ring_available(ffi.Pointer<VdAudioRing> ring) {
    return _vd_audio_ring_available(ring);
  }

  late final _vd_audio_ring_availablePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<VdAudioRing>)>>(
        'vd_audio_ring_available',
      );
  late final _vd_audio_ring_available = _vd_audio_ring_availablePtr
      .asFunction<int Function(ffi.Pointer<VdAudioRing>)>();

  int vd_audio_ring_space(ffi.Pointer<VdAudioRing> ring) {
    return _vd_audio_ring_space(ring);
  }

  late final _vd_audio_ring_spacePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<VdAudioRing>)>>(
        'vd_audio_ring_space',
      );
  late final _vd_audio_ring_space = _vd_audio_ring_spacePtr
      .asFunction<int Function(ffi.Pointer<VdAudioRing>)>();

  int vd_audio_ring_capacity(ffi.Pointer<VdAudioRing> ring) {
    return _vd_audio_ring_capacity(ring);
  }

  late final _vd_audio_ring_capacityPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<VdAudioRing>)>>(
        'vd_audio_ring_capacity',
      );
  late final _vd_audio_ring_capacity = _vd_audio_ring_capacityPtr
      .asFunction<int Function(ffi.Pointer<VdAudioRing>)>();

  /// Drops everything buffered. Called from the producer side on a seek; the
  /// consumer will read silence until the ring refills.
  void vd_audio_ring_clear(ffi.Pointer<VdAudioRing> ring) {
    return _vd_audio_ring_clear(ring);
  }

  late final _vd_audio_ring_clearPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdAudioRing>)>>(
        'vd_audio_ring_clear',
      );
  late final _vd_audio_ring_clear = _vd_audio_ring_clearPtr
      .asFunction<void Function(ffi.Pointer<VdAudioRing>)>();

  /// The multiplier a clip's sound gets `offset` ticks into a clip `duration`
  /// long, given its fade lengths. 0 outside the clip, 0 at each edge a fade
  /// reaches, 1 everywhere the fades do not touch.
  ///
  /// This is the same function as `ClipAudio.fadeShapeAt` in
  /// `app/lib/model/clip.dart`, and the two test the same table — change one and
  /// you must change the other. It is here rather than buried in the mixer
  /// because a fade the document draws and a fade the device plays being the same
  /// shape is not something to leave to two people reading the same prose.
  ///
  /// The ramps are linear in amplitude: the curve where the handle position means
  /// what it looks like it means.
  double vd_audio_fade_gain(
    int offset,
    int duration,
    int fade_in,
    int fade_out,
  ) {
    return _vd_audio_fade_gain(offset, duration, fade_in, fade_out);
  }

  late final _vd_audio_fade_gainPtr =
      _lookup<
        ffi.NativeFunction<ffi.Float Function(VdTick, VdTick, VdTick, VdTick)>
      >('vd_audio_fade_gain');
  late final _vd_audio_fade_gain = _vd_audio_fade_gainPtr
      .asFunction<double Function(int, int, int, int)>();

  /// The multiplier a clip's sound gets at `source_time`, given its volume line.
  /// 1 when there is no line; held flat at the first point's value before it and
  /// at the last point's after it; linear in amplitude in between.
  ///
  /// Held flat rather than ramped back to unity outside the points, because a
  /// curve that slid back to full volume before the first point would move audio
  /// the user never touched.
  ///
  /// The same function as `ClipAudio.automationAt` in `app/lib/model/clip.dart`,
  /// tested against the same table, for the same reason `vd_audio_fade_gain` is.
  ///
  /// `points` must be sorted by `source_time`. Two points at the same tick are a
  /// step, and the later one wins.
  double vd_audio_automation_gain(
    ffi.Pointer<VdVolumePoint> points,
    int count,
    int source_time,
  ) {
    return _vd_audio_automation_gain(points, count, source_time);
  }

  late final _vd_audio_automation_gainPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Float Function(ffi.Pointer<VdVolumePoint>, ffi.Int32, VdTick)
        >
      >('vd_audio_automation_gain');
  late final _vd_audio_automation_gain = _vd_audio_automation_gainPtr
      .asFunction<double Function(ffi.Pointer<VdVolumePoint>, int, int)>();

  ffi.Pointer<VdAudioRenderer> vd_audio_renderer_create(
    ffi.Pointer<ffi.Int32> out_result,
  ) {
    return _vd_audio_renderer_create(out_result);
  }

  late final _vd_audio_renderer_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VdAudioRenderer> Function(ffi.Pointer<ffi.Int32>)
        >
      >('vd_audio_renderer_create');
  late final _vd_audio_renderer_create = _vd_audio_renderer_createPtr
      .asFunction<
        ffi.Pointer<VdAudioRenderer> Function(ffi.Pointer<ffi.Int32>)
      >();

  void vd_audio_renderer_destroy(ffi.Pointer<VdAudioRenderer> renderer) {
    return _vd_audio_renderer_destroy(renderer);
  }

  late final _vd_audio_renderer_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdAudioRenderer>)>
      >('vd_audio_renderer_destroy');
  late final _vd_audio_renderer_destroy = _vd_audio_renderer_destroyPtr
      .asFunction<void Function(ffi.Pointer<VdAudioRenderer>)>();

  /// Takes the same render list the video side gets, and picks out the clips
  /// whose sources actually carry audio.
  int vd_audio_renderer_set_timeline(
    ffi.Pointer<VdAudioRenderer> renderer,
    ffi.Pointer<VdTimelineClip> clips,
    int clip_count,
  ) {
    return _vd_audio_renderer_set_timeline(renderer, clips, clip_count);
  }

  late final _vd_audio_renderer_set_timelinePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VdAudioRenderer>,
            ffi.Pointer<VdTimelineClip>,
            ffi.Int32,
          )
        >
      >('vd_audio_renderer_set_timeline');
  late final _vd_audio_renderer_set_timeline =
      _vd_audio_renderer_set_timelinePtr
          .asFunction<
            int Function(
              ffi.Pointer<VdAudioRenderer>,
              ffi.Pointer<VdTimelineClip>,
              int,
            )
          >();

  /// True when any clip in the timeline has audio. When false the engine keeps
  /// using its wall clock, because there is nothing to synchronise to.
  bool vd_audio_renderer_has_audio(ffi.Pointer<VdAudioRenderer> renderer) {
    return _vd_audio_renderer_has_audio(renderer);
  }

  late final _vd_audio_renderer_has_audioPtr =
      _lookup<
        ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<VdAudioRenderer>)>
      >('vd_audio_renderer_has_audio');
  late final _vd_audio_renderer_has_audio = _vd_audio_renderer_has_audioPtr
      .asFunction<bool Function(ffi.Pointer<VdAudioRenderer>)>();

  void vd_audio_renderer_start(
    ffi.Pointer<VdAudioRenderer> renderer,
    int position,
  ) {
    return _vd_audio_renderer_start(renderer, position);
  }

  late final _vd_audio_renderer_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<VdAudioRenderer>, VdTick)
        >
      >('vd_audio_renderer_start');
  late final _vd_audio_renderer_start = _vd_audio_renderer_startPtr
      .asFunction<void Function(ffi.Pointer<VdAudioRenderer>, int)>();

  void vd_audio_renderer_stop(ffi.Pointer<VdAudioRenderer> renderer) {
    return _vd_audio_renderer_stop(renderer);
  }

  late final _vd_audio_renderer_stopPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdAudioRenderer>)>
      >('vd_audio_renderer_stop');
  late final _vd_audio_renderer_stop = _vd_audio_renderer_stopPtr
      .asFunction<void Function(ffi.Pointer<VdAudioRenderer>)>();

  void vd_audio_renderer_seek(
    ffi.Pointer<VdAudioRenderer> renderer,
    int position,
  ) {
    return _vd_audio_renderer_seek(renderer, position);
  }

  late final _vd_audio_renderer_seekPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<VdAudioRenderer>, VdTick)
        >
      >('vd_audio_renderer_seek');
  late final _vd_audio_renderer_seek = _vd_audio_renderer_seekPtr
      .asFunction<void Function(ffi.Pointer<VdAudioRenderer>, int)>();

  /// The audio clock: the timeline position the device is playing right now.
  ///
  /// This is the master clock during playback. Audio cannot be stretched or
  /// skipped without the listener hearing it, whereas a video frame arriving a
  /// millisecond late is invisible — so video follows audio, never the reverse.
  int vd_audio_renderer_position(ffi.Pointer<VdAudioRenderer> renderer) {
    return _vd_audio_renderer_position(renderer);
  }

  late final _vd_audio_renderer_positionPtr =
      _lookup<
        ffi.NativeFunction<VdTick Function(ffi.Pointer<VdAudioRenderer>)>
      >('vd_audio_renderer_position');
  late final _vd_audio_renderer_position = _vd_audio_renderer_positionPtr
      .asFunction<int Function(ffi.Pointer<VdAudioRenderer>)>();

  /// Whether that position means anything yet.
  ///
  /// An audio clock only tells the time while something is draining it. With no
  /// device attached, or before the first pull after starting, the counter is
  /// standing still — and a caller that trusted it would freeze the picture.
  bool vd_audio_renderer_clock_valid(ffi.Pointer<VdAudioRenderer> renderer) {
    return _vd_audio_renderer_clock_valid(renderer);
  }

  late final _vd_audio_renderer_clock_validPtr =
      _lookup<
        ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<VdAudioRenderer>)>
      >('vd_audio_renderer_clock_valid');
  late final _vd_audio_renderer_clock_valid = _vd_audio_renderer_clock_validPtr
      .asFunction<bool Function(ffi.Pointer<VdAudioRenderer>)>();

  /// Fills `out` with `frames` of interleaved stereo, writing silence where the
  /// timeline has none. This is what the device callback calls; tests call it
  /// directly, which is why the device is not baked into the renderer.
  int vd_audio_renderer_pull(
    ffi.Pointer<VdAudioRenderer> renderer,
    ffi.Pointer<ffi.Float> out,
    int frames,
  ) {
    return _vd_audio_renderer_pull(renderer, out, frames);
  }

  late final _vd_audio_renderer_pullPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VdAudioRenderer>,
            ffi.Pointer<ffi.Float>,
            ffi.Int32,
          )
        >
      >('vd_audio_renderer_pull');
  late final _vd_audio_renderer_pull = _vd_audio_renderer_pullPtr
      .asFunction<
        int Function(ffi.Pointer<VdAudioRenderer>, ffi.Pointer<ffi.Float>, int)
      >();

  void vd_audio_renderer_stats(
    ffi.Pointer<VdAudioRenderer> renderer,
    ffi.Pointer<VdAudioStats> out,
  ) {
    return _vd_audio_renderer_stats(renderer, out);
  }

  late final _vd_audio_renderer_statsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<VdAudioRenderer>,
            ffi.Pointer<VdAudioStats>,
          )
        >
      >('vd_audio_renderer_stats');
  late final _vd_audio_renderer_stats = _vd_audio_renderer_statsPtr
      .asFunction<
        void Function(ffi.Pointer<VdAudioRenderer>, ffi.Pointer<VdAudioStats>)
      >();

  ffi.Pointer<VdAudioDevice> vd_audio_device_open(
    ffi.Pointer<VdAudioRenderer> renderer,
    ffi.Pointer<ffi.Int32> out_result,
  ) {
    return _vd_audio_device_open(renderer, out_result);
  }

  late final _vd_audio_device_openPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VdAudioDevice> Function(
            ffi.Pointer<VdAudioRenderer>,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('vd_audio_device_open');
  late final _vd_audio_device_open = _vd_audio_device_openPtr
      .asFunction<
        ffi.Pointer<VdAudioDevice> Function(
          ffi.Pointer<VdAudioRenderer>,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  void vd_audio_device_close(ffi.Pointer<VdAudioDevice> device) {
    return _vd_audio_device_close(device);
  }

  late final _vd_audio_device_closePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdAudioDevice>)>
      >('vd_audio_device_close');
  late final _vd_audio_device_close = _vd_audio_device_closePtr
      .asFunction<void Function(ffi.Pointer<VdAudioDevice>)>();

  int vd_audio_device_start(ffi.Pointer<VdAudioDevice> device) {
    return _vd_audio_device_start(device);
  }

  late final _vd_audio_device_startPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<VdAudioDevice>)>
      >('vd_audio_device_start');
  late final _vd_audio_device_start = _vd_audio_device_startPtr
      .asFunction<int Function(ffi.Pointer<VdAudioDevice>)>();

  int vd_audio_device_stop(ffi.Pointer<VdAudioDevice> device) {
    return _vd_audio_device_stop(device);
  }

  late final _vd_audio_device_stopPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<VdAudioDevice>)>
      >('vd_audio_device_stop');
  late final _vd_audio_device_stop = _vd_audio_device_stopPtr
      .asFunction<int Function(ffi.Pointer<VdAudioDevice>)>();

  /// Reads the audio of `path` end to end and builds the pyramid.
  ///
  /// Returns VD_OK, or a negative VdResult: VD_ERR_INVALID_ARG for the
  /// arguments, VD_ERR_OPEN for a file that will not open, VD_ERR_NO_STREAMS for
  /// one with no audio — which is where silent video lands, and is a fact about
  /// the file rather than a failure — and VD_ERR_DECODE when there is an audio
  /// stream that yields no samples. `out` is zeroed on every failure.
  int vd_peaks_analyze(ffi.Pointer<ffi.Char> path, ffi.Pointer<VdPeaks> out) {
    return _vd_peaks_analyze(path, out);
  }

  late final _vd_peaks_analyzePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<VdPeaks>)
        >
      >('vd_peaks_analyze');
  late final _vd_peaks_analyze = _vd_peaks_analyzePtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<VdPeaks>)>();

  /// Where level `level` starts in `buckets`, counted in buckets. Negative for a
  /// level the pyramid does not have.
  int vd_peaks_level_offset(ffi.Pointer<VdPeaks> peaks, int level) {
    return _vd_peaks_level_offset(peaks, level);
  }

  late final _vd_peaks_level_offsetPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<VdPeaks>, ffi.Int32)>
      >('vd_peaks_level_offset');
  late final _vd_peaks_level_offset = _vd_peaks_level_offsetPtr
      .asFunction<int Function(ffi.Pointer<VdPeaks>, int)>();

  /// Frees the buckets and zeroes the struct. Safe on a zeroed value, and safe
  /// twice.
  void vd_peaks_free(ffi.Pointer<VdPeaks> peaks) {
    return _vd_peaks_free(peaks);
  }

  late final _vd_peaks_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VdPeaks>)>>(
        'vd_peaks_free',
      );
  late final _vd_peaks_free = _vd_peaks_freePtr
      .asFunction<void Function(ffi.Pointer<VdPeaks>)>();
}

/// An instant or a duration, in ticks. Signed: negative offsets are legal.
typedef VdTick = ffi.Int64;
typedef DartVdTick = int;

/// An exact rate, e.g. {30000, 1001}. den > 0.
final class VdRational extends ffi.Struct {
  @ffi.Int32()
  external int num;

  @ffi.Int32()
  external int den;
}

/// The presets, in the order a picker offers them.
///
/// **A preset names the direction the clip travels, not the edge it comes
/// from.** `VD_ANIM_SLIDE_UP` moves upwards both times: on the way in it rises
/// into place from below, and on the way out it carries on and leaves through
/// the top. One rule for both halves, where "in from the left, out to the left"
/// would be two — and the second one nobody can predict.
///
/// Values cross the FFI boundary as integers, so these may be appended to and
/// never reordered.
enum VdAnimPreset {
  VD_ANIM_NONE(0),

  /// Opacity alone. The one that suits anything.
  VD_ANIM_FADE(1),
  VD_ANIM_SLIDE_UP(2),
  VD_ANIM_SLIDE_DOWN(3),
  VD_ANIM_SLIDE_LEFT(4),
  VD_ANIM_SLIDE_RIGHT(5),

  /// Overshoots and settles back. The only preset that is ever larger than its
  /// resting size, which is what makes it read as a pop rather than a grow.
  VD_ANIM_POP(6),

  /// Grows from small. Like pop without the overshoot.
  VD_ANIM_ZOOM(7),

  /// A turn and a grow together.
  VD_ANIM_SPIN(8),

  /// Reveals the text a character at a time. Does nothing at all to a clip that
  /// has no text — it is in this list rather than in a list of its own because
  /// it is chosen from the same menu, and a preset that quietly does nothing on
  /// a video clip is better than a menu that changes shape depending on what is
  /// selected.
  VD_ANIM_TYPEWRITER(9);

  final int value;
  const VdAnimPreset(this.value);

  static VdAnimPreset fromValue(int value) => switch (value) {
    0 => VD_ANIM_NONE,
    1 => VD_ANIM_FADE,
    2 => VD_ANIM_SLIDE_UP,
    3 => VD_ANIM_SLIDE_DOWN,
    4 => VD_ANIM_SLIDE_LEFT,
    5 => VD_ANIM_SLIDE_RIGHT,
    6 => VD_ANIM_POP,
    7 => VD_ANIM_ZOOM,
    8 => VD_ANIM_SPIN,
    9 => VD_ANIM_TYPEWRITER,
    _ => throw ArgumentError('Unknown value for VdAnimPreset: $value'),
  };
}

/// What a preset produces at one instant.
///
/// Everything here **composes with** what the clip already asked for rather
/// than replacing it: offsets add, scale multiplies, rotation adds, opacity
/// multiplies. A caption parked at the bottom of the frame that slides up has
/// to slide up from below *its own* position, not from below the middle.
final class VdAnimValue extends ffi.Struct {
  /// Added to the clip's own offset, as a fraction of the output's width and
  /// height — the same units VdTransform uses.
  @ffi.Float()
  external double offset_x;

  @ffi.Float()
  external double offset_y;

  /// Multiplied into the clip's own scale. 1 is at rest.
  @ffi.Float()
  external double scale;

  /// Added to the clip's own rotation.
  @ffi.Float()
  external double rotation_degrees;

  /// Multiplied into the clip's own opacity. 1 is at rest.
  @ffi.Float()
  external double opacity;

  /// How much of the text to show, 0..1. 1 is all of it, which is what every
  /// preset but the typewriter produces.
  @ffi.Float()
  external double reveal;
}

/// The in and out animations on one clip.
final class VdClipAnim extends ffi.Struct {
  @ffi.UnsignedInt()
  external int in_presetAsInt;

  VdAnimPreset get in_preset => VdAnimPreset.fromValue(in_presetAsInt);

  @VdTick()
  external int in_duration;

  @ffi.UnsignedInt()
  external int out_presetAsInt;

  VdAnimPreset get out_preset => VdAnimPreset.fromValue(out_presetAsInt);

  @VdTick()
  external int out_duration;
}

enum VdResult {
  VD_OK(0),

  /// could not open the file at all
  VD_ERR_OPEN(-1),

  /// opened, but nothing playable inside
  VD_ERR_NO_STREAMS(-2),
  VD_ERR_INVALID_ARG(-3),
  VD_ERR_UNSUPPORTED(-4),

  /// opened, but a frame could not be produced
  VD_ERR_DECODE(-5);

  final int value;
  const VdResult(this.value);

  static VdResult fromValue(int value) => switch (value) {
    0 => VD_OK,
    -1 => VD_ERR_OPEN,
    -2 => VD_ERR_NO_STREAMS,
    -3 => VD_ERR_INVALID_ARG,
    -4 => VD_ERR_UNSUPPORTED,
    -5 => VD_ERR_DECODE,
    _ => throw ArgumentError('Unknown value for VdResult: $value'),
  };
}

final class VdProbeInfo extends ffi.Struct {
  @ffi.Bool()
  external bool has_video;

  @ffi.Bool()
  external bool has_audio;

  /// Duration of the longest stream, in project ticks. 0 when the container
  /// does not say — a stream, or a damaged file.
  @VdTick()
  external int duration;

  /// Coded dimensions, before rotation.
  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  /// Display rotation from the container: 0, 90, 180 or 270.
  @ffi.Int32()
  external int rotation_degrees;

  /// Nominal frame rate. When `variable_frame_rate` is set this is the average,
  /// and individual frames will not land on it — they are normalised to the
  /// project timebase at decode time.
  external VdRational frame_rate;

  @ffi.Bool()
  external bool variable_frame_rate;

  @ffi.Int32()
  external int audio_channels;

  @ffi.Int32()
  external int audio_sample_rate;

  /// Sample aspect ratio; {1,1} for square pixels.
  external VdRational pixel_aspect;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> video_codec;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> audio_codec;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> format_name;
}

final class VdDecoder extends ffi.Opaque {}

enum VdPixelFormat {
  /// Zero-copy from VideoToolbox: an IOSurface-backed NV12 buffer, ready for
  /// the Metal compositor to sample directly.
  VD_PIXEL_NV12(0),

  /// Software decode, copied into a planar buffer. Slower, and the compositor
  /// has to sample it differently.
  VD_PIXEL_YUV420P(1),

  /// Not something a decoder produces: premultiplied BGRA, which is what a
  /// generated layer — a caption, a shape — arrives as. It lives in this enum
  /// rather than in one of its own because VdLayer::format is the only thing
  /// that reads it, and the compositor should not have to be told twice what
  /// kind of pixels it is being handed.
  VD_PIXEL_BGRA(2);

  final int value;
  const VdPixelFormat(this.value);

  static VdPixelFormat fromValue(int value) => switch (value) {
    0 => VD_PIXEL_NV12,
    1 => VD_PIXEL_YUV420P,
    2 => VD_PIXEL_BGRA,
    _ => throw ArgumentError('Unknown value for VdPixelFormat: $value'),
  };
}

final class VdDecoderOptions extends ffi.Struct {
  /// 1 to try VideoToolbox. Falls back to software if the codec cannot be
  /// hardware-decoded; check VdFrame::hardware to see what actually happened.
  @ffi.Int32()
  external int hardware;

  /// Decoded frames to retain. 0 picks a default sized for scrubbing back and
  /// forth across a second or so of footage.
  @ffi.Int32()
  external int cache_capacity;
}

/// The YCbCr matrix a source was encoded with. Getting this wrong does not
/// look broken, it looks *slightly off* — which is worse, because nobody
/// reports it and every export inherits it.
enum VdColorMatrix {
  VD_MATRIX_BT601(0),
  VD_MATRIX_BT709(1),
  VD_MATRIX_BT2020(2);

  final int value;
  const VdColorMatrix(this.value);

  static VdColorMatrix fromValue(int value) => switch (value) {
    0 => VD_MATRIX_BT601,
    1 => VD_MATRIX_BT709,
    2 => VD_MATRIX_BT2020,
    _ => throw ArgumentError('Unknown value for VdColorMatrix: $value'),
  };
}

final class VdFrame extends ffi.Struct {
  /// CVPixelBufferRef, retained. Release with vd_frame_release, always, on
  /// every path — the cache holds its own reference and does not care about
  /// yours.
  external ffi.Pointer<ffi.Void> pixel_buffer;

  @ffi.UnsignedInt()
  external int formatAsInt;

  VdPixelFormat get format => VdPixelFormat.fromValue(formatAsInt);

  /// The presentation interval this frame covers: [pts, pts + duration).
  ///
  /// `duration` runs to the presentation time of the frame that follows, which
  /// is not always what the container claims — muxers write per-frame durations
  /// in decode order, so with B-frames they land on the wrong frames, and on a
  /// variable-rate source the difference is frames from the future rather than
  /// a rounding error. The last frame of a source is the exception: nothing
  /// follows it, so it carries the nominal duration and queries past it clamp.
  @VdTick()
  external int pts;

  @VdTick()
  external int duration;

  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  @ffi.Bool()
  external bool hardware;

  @ffi.UnsignedInt()
  external int color_matrixAsInt;

  VdColorMatrix get color_matrix => VdColorMatrix.fromValue(color_matrixAsInt);

  /// True for 0-255 luma, false for the 16-235 video range most sources use.
  @ffi.Bool()
  external bool full_range;
}

/// --- telemetry -------------------------------------------------------------
final class VdDecoderStats extends ffi.Struct {
  @ffi.Int64()
  external int frames_decoded;

  @ffi.Int64()
  external int cache_hits;

  @ffi.Int64()
  external int cache_misses;

  @ffi.Int64()
  external int seeks;

  @ffi.Int64()
  external int decode_errors;
}

final class VdCompositor extends ffi.Opaque {}

/// How a source that does not match the output aspect is placed.
enum VdFitMode {
  /// whole frame visible, letterboxed
  VD_FIT_CONTAIN(0),

  /// fills the output, edges cropped
  VD_FIT_COVER(1),

  /// ignores aspect
  VD_FIT_STRETCH(2),

  /// Whole frame visible, and the bars filled with a blurred, cover-fitted
  /// copy of the same picture rather than black. Costs three extra passes, and
  /// only when there are bars to fill — a clip that already fills the output
  /// takes the ordinary path.
  VD_FIT_BLUR(3);

  final int value;
  const VdFitMode(this.value);

  static VdFitMode fromValue(int value) => switch (value) {
    0 => VD_FIT_CONTAIN,
    1 => VD_FIT_COVER,
    2 => VD_FIT_STRETCH,
    3 => VD_FIT_BLUR,
    _ => throw ArgumentError('Unknown value for VdFitMode: $value'),
  };
}

/// What a clip does to itself before it is composited: where it sits, how big
/// it is, which way up, and how much of it shows.
///
/// Every field is defined so that **a zeroed struct is the identity**. A caller
/// that does not care about transforms can `memset` its layers and never learn
/// this field exists, which is worth more than the two lines it costs to treat
/// a zero scale as one.
///
/// Applied in this order, about the layer's own centre: crop, then the fit the
/// mode asked for, then scale, then rotation, then offset. Crop first because
/// cropping changes the aspect ratio, and a fit computed before it would letter
/// box the part that was thrown away.
final class VdTransform extends ffi.Struct {
  /// Offset from the centre of the output, as a fraction of the output's own
  /// width and height. {0,0} is centred; {0.5,0} is off the right edge.
  @ffi.Float()
  external double offset_x;

  @ffi.Float()
  external double offset_y;

  /// Uniform multiplier on the fitted size. 0 and 1 both mean "as fitted".
  @ffi.Float()
  external double scale;

  /// Extra clockwise rotation in degrees, on top of whatever the source's own
  /// orientation metadata already asked for. Any angle, not just quarter turns.
  @ffi.Float()
  external double rotation_degrees;

  /// The part of the *display-oriented* source to show, normalised, origin top
  /// left. A zeroed width or height means the whole thing.
  @ffi.Float()
  external double crop_x;

  @ffi.Float()
  external double crop_y;

  @ffi.Float()
  external double crop_w;

  @ffi.Float()
  external double crop_h;

  /// Mirrored horizontally / vertically, in display orientation.
  @ffi.Bool()
  external bool flip_h;

  @ffi.Bool()
  external bool flip_v;
}

final class VdLayer extends ffi.Struct {
  /// CVPixelBufferRef from vd_decoder_frame_at. Borrowed for the duration of
  /// the call; the compositor does not retain it.
  external ffi.Pointer<ffi.Void> pixel_buffer;

  @ffi.UnsignedInt()
  external int formatAsInt;

  VdPixelFormat get format => VdPixelFormat.fromValue(formatAsInt);

  /// Clockwise degrees to rotate for display: 0, 90, 180, 270.
  @ffi.Int32()
  external int rotation_degrees;

  /// The source's sample aspect: how much wider one of its pixels is than it
  /// is tall. {0,0} and {1,1} both mean square, so a caller with square pixels
  /// can leave it zeroed. Applied before the rotation, because a turn swaps
  /// which axis the stretch is on.
  ///
  /// This is what makes a 4:3 DVD frame stored as 720x480 come out 4:3 rather
  /// than squeezed to 3:2. It belongs on the layer rather than being folded
  /// into the coded size by the decoder, because the pixels really are 720
  /// across — only the shape they are meant to be shown at differs.
  external VdRational pixel_aspect;

  /// Copied straight from the VdFrame the buffer came out of.
  @ffi.UnsignedInt()
  external int color_matrixAsInt;

  VdColorMatrix get color_matrix => VdColorMatrix.fromValue(color_matrixAsInt);

  @ffi.Bool()
  external bool full_range;

  @ffi.UnsignedInt()
  external int fitAsInt;

  VdFitMode get fit => VdFitMode.fromValue(fitAsInt);

  /// 0..1
  @ffi.Float()
  external double opacity;

  /// Where this layer goes and how much of it shows. A zeroed transform is the
  /// identity, so this may be ignored entirely.
  external VdTransform transform;
}

/// What gets drawn inside the box.
///
/// **One box, four shapes.** Every kind is drawn inside the same rectangle —
/// `width` by `height`, centred in the frame — which is what makes the two size
/// numbers mean the same thing in all of them. A rectangle fills the box, an
/// ellipse is inscribed in it, and a line runs across it from the middle of the
/// left edge to the middle of the right.
///
/// A rounded rectangle is `VD_SHAPE_RECT` with a `corner`, and a circle is
/// `VD_SHAPE_ELLIPSE` with equal sides, rather than kinds of their own: both
/// are one slider away from the shape beside them, and a picker with six
/// entries where four would do makes the reader look for a difference that is
/// not there.
///
/// Values cross the FFI boundary as integers, so these may be appended to and
/// never reordered.
enum VdShapeKind {
  VD_SHAPE_RECT(0),
  VD_SHAPE_ELLIPSE(1),

  /// The stroke *is* the shape: a line has no interior, so `fill_color` says
  /// nothing about it and a line with no stroke width draws nothing — the same
  /// rule a rectangle with no fill already follows.
  VD_SHAPE_LINE(2),

  /// A line with a head on its right end. Right, because that is the direction
  /// the clip's own rotation turns towards, so "which way does it point" has
  /// one answer and it is the transform's.
  VD_SHAPE_ARROW(3);

  final int value;
  const VdShapeKind(this.value);

  static VdShapeKind fromValue(int value) => switch (value) {
    0 => VD_SHAPE_RECT,
    1 => VD_SHAPE_ELLIPSE,
    2 => VD_SHAPE_LINE,
    3 => VD_SHAPE_ARROW,
    _ => throw ArgumentError('Unknown value for VdShapeKind: $value'),
  };
}

/// Everything about how one shape looks.
///
/// All scalars, unlike VdTextSpec — there is no string in a rectangle — which
/// is why the copy below is a memcpy and the comparison is worth reading.
///
/// Colours are 0xAARRGGBB, straight (not premultiplied). Alpha 0 means *off*:
/// a fill with no alpha draws no fill, a stroke with none draws no outline, a
/// shadow colour with none casts no shadow. One rule rather than three booleans
/// nobody would keep in step with the colours beside them.
final class VdShapeSpec extends ffi.Struct {
  @ffi.UnsignedInt()
  external int kindAsInt;

  VdShapeKind get kind => VdShapeKind.fromValue(kindAsInt);

  /// The box, as fractions of the output height. Equal values are a square —
  /// and so a circle, for an ellipse — in a 16:9 project and in a 9:16 one.
  @ffi.Float()
  external double width;

  @ffi.Float()
  external double height;

  /// How round the corners of a rectangle are: 0 is square, 1 is as round as
  /// the box allows, which is a pill on an oblong and a circle on a square. A
  /// proportion rather than a length, so a rectangle keeps its corners when it
  /// is resized. Ignored by every kind but VD_SHAPE_RECT.
  @ffi.Float()
  external double corner;

  /// Ignored by VD_SHAPE_LINE and VD_SHAPE_ARROW, which have no interior.
  @ffi.Uint32()
  external int fill_color;

  /// Drawn over the fill, straddling the edge, which is what every drawing
  /// program does and what keeps a filled shape the size it says it is.
  @ffi.Uint32()
  external int stroke_color;

  @ffi.Float()
  external double stroke_width;

  /// Cast by the whole shape — fill and stroke together, as one silhouette —
  /// onto whatever is behind it. +y is down, the direction a light above the
  /// frame throws it.
  @ffi.Uint32()
  external int shadow_color;

  @ffi.Float()
  external double shadow_dx;

  @ffi.Float()
  external double shadow_dy;

  @ffi.Float()
  external double shadow_blur;

  /// How much of an arrow is head, as a fraction of its length. A proportion
  /// for the same reason `corner` is one: an arrow that is lengthened should
  /// still look like an arrow. Ignored by every kind but VD_SHAPE_ARROW.
  @ffi.Float()
  external double head_size;
}

/// Where each line sits inside the text block. The block itself is centred in
/// the frame and moved by the clip's transform; this only decides what happens
/// to a short line next to a long one.
enum VdTextAlign {
  VD_TEXT_ALIGN_LEFT(0),
  VD_TEXT_ALIGN_CENTER(1),
  VD_TEXT_ALIGN_RIGHT(2);

  final int value;
  const VdTextAlign(this.value);

  static VdTextAlign fromValue(int value) => switch (value) {
    0 => VD_TEXT_ALIGN_LEFT,
    1 => VD_TEXT_ALIGN_CENTER,
    2 => VD_TEXT_ALIGN_RIGHT,
    _ => throw ArgumentError('Unknown value for VdTextAlign: $value'),
  };
}

/// Everything about how one caption looks.
///
/// Colours are 0xAARRGGBB, straight (not premultiplied) — the document writes
/// them and a human reads them, and premultiplied colour is neither. Alpha 0
/// means *off* for the two optional parts: a shadow colour with no alpha casts
/// no shadow, a box colour with no alpha draws no box. That is one rule rather
/// than two booleans nobody would keep in step with the colours beside them.
final class VdTextSpec extends ffi.Struct {
  /// UTF-8, NUL terminated. NULL or empty renders a transparent frame, which
  /// is what a caption someone has not typed into yet should look like.
  external ffi.Pointer<ffi.Char> text;

  /// Family name as the font file reports it — "Inter", "Playfair Display".
  /// NULL, empty, or a family nothing was registered under falls back to the
  /// system's own, so a project made on a machine with a pack installed still
  /// opens somewhere it is not.
  external ffi.Pointer<ffi.Char> font;

  /// Cap height of the type as a fraction of the output height. 0.08 is a
  /// readable caption on a 16:9 frame.
  @ffi.Float()
  external double size;

  @ffi.Uint32()
  external int color;

  /// An outline, drawn under the fill so only its outer half shows. Width is a
  /// fraction of the font size, which is also how CoreText expresses it.
  @ffi.Uint32()
  external int stroke_color;

  @ffi.Float()
  external double stroke_width;

  /// Cast by the ink — the fill and its outline together — onto whatever is
  /// behind it, including the box. Offsets and blur are fractions of the font
  /// size; +y is down, the direction a light above the frame throws it.
  @ffi.Uint32()
  external int shadow_color;

  @ffi.Float()
  external double shadow_dx;

  @ffi.Float()
  external double shadow_dy;

  @ffi.Float()
  external double shadow_blur;

  /// A rounded rectangle behind the whole block, inset by `box_padding` on
  /// every side. Padding and corner radius are fractions of the font size, so
  /// the box keeps its proportions as the type grows.
  @ffi.Uint32()
  external int box_color;

  @ffi.Float()
  external double box_padding;

  @ffi.Float()
  external double box_radius;

  /// Extra space between glyphs, as a fraction of the font size. Negative
  /// tightens.
  @ffi.Float()
  external double letter_spacing;

  /// Multiple of the font's own line height. 0 and 1 both mean "as the font
  /// asked for".
  @ffi.Float()
  external double line_spacing;

  /// How much of the output's width the block may fill before it wraps, as a
  /// fraction. 0 means the default, which leaves a margin — text that touches
  /// the edge of the frame reads as a mistake.
  @ffi.Float()
  external double max_width;

  @ffi.UnsignedInt()
  external int alignAsInt;

  VdTextAlign get align => VdTextAlign.fromValue(alignAsInt);
}

final class VdEngine extends ffi.Opaque {}

final class VdAudioRenderer extends ffi.Opaque {}

enum VdPlaybackState {
  VD_STATE_IDLE(0),
  VD_STATE_PLAYING(1),
  VD_STATE_PAUSED(2),
  VD_STATE_ENDED(3);

  final int value;
  const VdPlaybackState(this.value);

  static VdPlaybackState fromValue(int value) => switch (value) {
    0 => VD_STATE_IDLE,
    1 => VD_STATE_PLAYING,
    2 => VD_STATE_PAUSED,
    3 => VD_STATE_ENDED,
    _ => throw ArgumentError('Unknown value for VdPlaybackState: $value'),
  };
}

/// One point on a clip's volume line.
///
/// `source_time` is in the source's own time — the same coordinate as
/// `source_in` — rather than an offset into the clip, so that trimming a clip
/// slides the window over the automation instead of dragging the automation
/// along with it. A duck stays on the word it was drawn for.
final class VdVolumePoint extends ffi.Struct {
  @VdTick()
  external int source_time;

  @ffi.Float()
  external double value;
}

final class VdTimelineClip extends ffi.Struct {
  /// Absolute path to the source file, or NULL for a clip that generates its
  /// own picture — see `text` and `shape`. Copied on set_timeline; the caller
  /// keeps ownership of its own string.
  external ffi.Pointer<ffi.Char> path;

  /// A caption instead of a file. NULL for every clip that has a `path`, and
  /// the three are exclusive: a clip is a window onto a source, or it is one of
  /// the two things the engine draws, and never two of them at once.
  ///
  /// The spec is copied on set_timeline, strings and all, and the raster it
  /// produces is kept for as long as the clip's spec is unchanged — the same
  /// bargain `path` gets with its decoder, and for the same reason: nudging a
  /// clip must not cost a re-layout of every caption on the timeline.
  external ffi.Pointer<VdTextSpec> text;

  /// A rectangle, an ellipse, a line or an arrow instead of a file. Copied and
  /// cached on exactly the terms `text` is: a shape whose spec did not change
  /// keeps the pixels it already had. See vd_shape.h.
  external ffi.Pointer<VdShapeSpec> shape;

  /// position on the timeline
  @VdTick()
  external int start;

  /// length on the timeline
  @VdTick()
  external int duration;

  /// offset into the source
  @VdTick()
  external int source_in;

  /// Compositing order: lower renders first, so 0 is the main track.
  @ffi.Int32()
  external int track;

  @ffi.Float()
  external double opacity;

  @ffi.UnsignedInt()
  external int fitAsInt;

  VdFitMode get fit => VdFitMode.fromValue(fitAsInt);

  /// Where this clip sits inside the frame. A zeroed transform is the identity,
  /// so a caller with nothing to say about it can leave the field alone.
  external VdTransform transform;

  /// How it arrives and how it leaves. A zeroed VdClipAnim is "no animation",
  /// so this is another field a caller can ignore.
  ///
  /// Evaluated per frame and composed with `transform` rather than replacing
  /// it: a caption parked at the bottom that slides up slides up from below
  /// its own position. See vd_anim.h.
  external VdClipAnim anim;

  /// False for a clip that contributes only sound: one on an audio lane, or a
  /// file with no picture in it. The compositor skips it rather than opening a
  /// decoder that will never yield a frame and holding a cache slot with it.
  ///
  /// The caller is told to say, rather than the engine probing to find out,
  /// because the document already knows — and a music bed should not cost a
  /// file open on every edit to establish that it has no video.
  @ffi.Bool()
  external bool has_video;

  /// Linear gain on this clip's sound, 0 for silent. Mute is spelled 0 here:
  /// the document keeps the difference between "muted" and "turned down",
  /// because unmuting has to give the level back, but by the time it reaches
  /// the engine that distinction has been decided and only the number matters.
  @ffi.Float()
  external double gain;

  /// Ramps from silence over `fade_in` at the head and to silence over
  /// `fade_out` at the tail. Ticks, like every other length that crosses here.
  @VdTick()
  external int fade_in;

  @VdTick()
  external int fade_out;

  /// The volume line: gain over the source, sorted by `source_time`, and a
  /// multiplier on `gain` rather than a replacement for it. NULL and 0 mean a
  /// clip nobody has automated, which is almost all of them.
  ///
  /// The only thing on this struct that is not a scalar, because it is the only
  /// thing whose length the document decides. Copied on set_timeline, like
  /// `path`; the caller keeps ownership of its own array.
  external ffi.Pointer<VdVolumePoint> volume_points;

  @ffi.Int32()
  external int volume_point_count;
}

final class VdTimeline extends ffi.Struct {
  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  external VdRational frame_rate;

  external ffi.Pointer<VdTimelineClip> clips;

  @ffi.Int32()
  external int clip_count;
}

final class VdEngineOptions extends ffi.Struct {
  /// 0 to skip opening an output device. The audio path still decodes and
  /// mixes, and vd_engine_audio_renderer can still be pulled — which is how
  /// the tests exercise A/V sync without making a noise, and how a headless
  /// export will avoid touching the sound card.
  @ffi.Int32()
  external int audio_output;
}

typedef VdFrameCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Void> context,
);
typedef DartVdFrameCallbackFunction = void Function(
  ffi.Pointer<ffi.Void> context,
);

/// Called from the render thread each time a new frame is published. The
/// plugin hooks this to -[FlutterTextureRegistry textureFrameAvailable:].
/// Must not block and must not call back into the engine.
typedef VdFrameCallback =
    ffi.Pointer<ffi.NativeFunction<VdFrameCallbackFunction>>;

final class VdEngineStats extends ffi.Struct {
  @ffi.Int64()
  external int frames_presented;

  /// Frames whose deadline had already passed when they were ready. This is
  /// the number that says whether playback is actually keeping up.
  @ffi.Int64()
  external int frames_late;

  @ffi.Double()
  external double composite_ms_avg;

  @ffi.Double()
  external double present_fps;

  @VdTick()
  external int position;

  @VdTick()
  external int duration;

  @ffi.Int32()
  external int state;

  @ffi.Int32()
  external int open_decoders;

  @ffi.Int32()
  external int active_layers;

  @ffi.Double()
  external double last_seek_ms;

  /// True when the timeline has audio, and therefore when the audio clock is
  /// the one driving playback.
  @ffi.Bool()
  external bool audio_available;

  /// Times the device asked for audio that had not been decoded yet. Unlike a
  /// late video frame, every one of these is audible.
  @ffi.Int64()
  external int audio_underruns;

  @ffi.Int32()
  external int audio_buffered_frames;

  /// Renders that happened because something asked for one rather than because
  /// the playhead reached a new frame. A seek is one; a steady stream of them
  /// during playback means something is spuriously repainting.
  @ffi.Int64()
  external int forced_renders;

  /// Times the playhead was seen to move backwards during playback. The audio
  /// clock and the wall clock do not tick at quite the same rate, so a position
  /// read that falls back from one to the other can dip — and a dip across a
  /// frame boundary would republish a frame that has already been shown.
  @ffi.Int64()
  external int clock_regressions;

  /// Captions laid out since the engine started. This is the number that says
  /// whether the raster cache is working: it should tick once per caption per
  /// edit that changed one, and never during playback. A steady stream of them
  /// means every frame is re-running Core Text, which is the whole thing the
  /// cache exists to prevent.
  @ffi.Int64()
  external int text_rasters;

  /// Shapes drawn, on the same terms and read the same way. A counter of its
  /// own rather than a shared "generated rasters", because the two answer
  /// different questions: a caption's raster is the expensive one and the one
  /// an animation can invalidate per character, and folding a shape's into it
  /// would blunt exactly the measurement text_rasters exists to make.
  @ffi.Int64()
  external int shape_rasters;
}

final class VdThumbnail extends ffi.Struct {
  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  /// Tightly packed BGRA, width * height * 4 bytes. Owned by the caller;
  /// release with vd_thumbnail_free.
  external ffi.Pointer<ffi.Uint8> pixels;
}

final class VdAudioSource extends ffi.Opaque {}

final class VdAudioRing extends ffi.Opaque {}

final class VdAudioStats extends ffi.Struct {
  @ffi.Int64()
  external int frames_rendered;

  /// Times the device asked for audio that had not been decoded yet. Any
  /// number above zero here is audible.
  @ffi.Int64()
  external int underruns;

  @ffi.Int32()
  external int buffered_frames;

  @ffi.Int32()
  external int open_sources;
}

final class VdAudioDevice extends ffi.Opaque {}

/// The pyramid. `buckets` holds every level concatenated finest-first, two
/// int16 per bucket — the minimum then the maximum sample in it, scaled by
/// 32767 and clamped to +/-32767.
///
/// Signed, and both ends kept, because sound is not symmetrical: a rectified
/// waveform drawn from absolute values looks tidier and hides which way a
/// transient went, and mirroring one half is a picture of a file nobody has.
final class VdPeaks extends ffi.Struct {
  @ffi.Int32()
  external int level_count;

  /// Level 0's bucket size, in audio frames. Level n's is this << n.
  @ffi.Int32()
  external int frames_per_bucket;

  @ffi.Int32()
  external int sample_rate;

  /// Channels the peaks were taken across. The minimum and maximum are over
  /// every sample of every channel in the bucket, not over a mono downmix:
  /// summing to mono lets two out-of-phase channels cancel into a flat line
  /// for audio that is plainly audible.
  @ffi.Int32()
  external int channels;

  /// Audio frames scanned, and the same length in ticks.
  @ffi.Int64()
  external int frame_count;

  @VdTick()
  external int duration;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Int32> bucket_counts;

  /// Sum of bucket_counts; `buckets` holds twice this many int16.
  @ffi.Int64()
  external int bucket_total;

  /// Owned by the caller; release with vd_peaks_free.
  external ffi.Pointer<ffi.Int16> buckets;
}

const int VD_TICKS_PER_SECOND = 120000;

const int VD_NANOS_PER_SECOND = 1000000000;

const int VD_AUDIO_SAMPLE_RATE = 48000;

const int VD_AUDIO_CHANNELS = 2;

const int VD_PEAKS_FRAMES_PER_BUCKET = 128;

const int VD_PEAKS_MAX_LEVELS = 16;
