# Turns a binary file into a C array, so a compiled shader library ships inside
# the engine rather than as a resource something has to locate at runtime.
#
#   cmake -DINPUT=x.metallib -DOUTPUT=x.c -DSYMBOL=name -P embed_binary.cmake
file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" hex_length)
math(EXPR byte_count "${hex_length} / 2")
string(REGEX REPLACE "(..)" "0x\\1," body "${hex}")
file(WRITE "${OUTPUT}"
"// GENERATED by cmake/embed_binary.cmake — do not edit.
#include <stddef.h>

const unsigned char ${SYMBOL}[] = {${body}};
const size_t ${SYMBOL}_size = ${byte_count};
")
